### ISSUE TITLE
New component: Avatar

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1092]
## Related information and insight
- Atlassian: https://atlassian.design/components/avatar/
- Ant: https://www.antforfigma.com/components/avatar

## Specification and requirements
- Should come in 3 sizes: `Small`, `medium`, `large`. 
- _Add specification and requirements_
- Should support initals, icons and an graphical elements (`picture`, `img`)
```[tasklist]
### Tasks
- [x] Avatar: Write about specification, requirements and scope in this issue
- [ ] https://github.com/digdir/designsystem/issues/1096
- [ ] https://github.com/digdir/designsystem/issues/1097
- [ ] https://github.com/digdir/designsystem/issues/1098
```
