### ISSUE TITLE
New component: Skeleton

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1094]
## Related information and insight
- Entur: https://design.entur.no/komponenter/feedback/skeleton
- Nord Designsystem: https://nordhealth.design/components/skeleton/
- Aksel: https://aksel.nav.no/komponenter/core/skeleton#skeletondemo-text-size
- Chakra: https://chakra-ui.com/docs/components/skeleton/usage

## Specification and requirements
- The Skeleton Component should include a subtle animation to indicate activity.
  - "Shine" animation or opacity animation is to be decided -> decided on opacity for the sake of simplicity 
  - The component should support reduced motion which turns off the animation
- The implementation is to be a compound component with 3 "variants":
  - Skeleton.Circle
  - Skeleton.Rectangle
  - Skeleton.Text
- The component should support sizing based on 4 cases:
  - Height and width props should be optional, but override all other sizing if set
  - The height should be inherited from a parent components fontsize
  - The height and width should encompass any possible children
  - Skeleton can be used in the "as" prop of other components (ex: <Header as='Skeleton'>)
- Rectangles should have rounded corners, text should have rounded side edges

```[tasklist]
### Tasks
- [x] Skeleton: Write about specification, requirements and scope in this issue
- [ ] https://github.com/digdir/designsystem/issues/1099
- [ ] https://github.com/digdir/designsystem/issues/1100
- [ ] https://github.com/digdir/designsystem/issues/1101
```

**Comment by mrosvik** [comment]
The `skeleton` component is ready for use: https://storybook.designsystemet.no/?path=/docs/felles-loaders-skeleton--docs
