### ISSUE TITLE
New component: Breadcrumb

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1095]
## Related information and insight
- Carbon: https://carbondesignsystem.com/components/breadcrumb/usage/
- Fælles designsystem: https://designsystem.dk/komponenter/broedkrumme/

## Specification and requirements
- Should come in 3 sizes: `Small`, `medium`, `large`. 
- Should use the link-component. 
- Design for small and large screen sizes. 
- A separator should provide clearly distinguishes between each page.

```[tasklist]
### Tasks
- [x] Breadcrumb: Write about specification, requirements and scope in this issue
- [ ] https://github.com/digdir/designsystem/issues/1102
- [ ] https://github.com/digdir/designsystem/issues/1103
- [ ] https://github.com/digdir/designsystem/issues/1104
```

**Comment by eirikbacker** [comment]
UU:
- Burde ha struktur `<nav><ol><li><a>`
- `<nav>` må ha en deskriptiv `aria-label` (f.eks "Sidens plassering" - ikke "Brødsmuler")
- Siste lenke burde ha `aria-current="page"`
- Skille-tegnet må skjules for skjermlesere (merk at `content` leses opp i `::before` og `::after` (med mindre man bruker `content: '' / 'Noe mer her'` som ikke støttes av Firefox enda))
