### ISSUE TITLE
Storefront: New design for the frontpage

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystemet#1138]
- [x] Design in figma
- [ ] Develop frontpage

The design is done, just need to finish the animations.

There is an old PR on this that I used for testing. It might be easier to start with a new one.
```[tasklist]
### Tasks
- [x] Design frontpage in figma
- [ ] Develop new frontpage in react
```

Figma: https://www.figma.com/file/hpNSt9jMeVTH46Fh9TENBE/Storefront?type=design&node-id=1377%3A7941&mode=design&t=WVqP0tmdFdSjRkhP-1
