### ISSUE TITLE
Refactor selection controls to CSS

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1224]
Due to reasons listed in #769 we have decided to refactor our selection controls to pure CSS instead of using inline svg icons. 

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/1223
- [ ] https://github.com/digdir/designsystem/issues/1222
- [ ] https://github.com/digdir/designsystem/issues/1221
- [ ] https://github.com/digdir/designsystem/issues/769
- [ ] https://github.com/digdir/designsystemet/issues/1115
- [ ] https://github.com/digdir/designsystemet/issues/898
- [ ] https://github.com/digdir/designsystemet/issues/1361
```

**Comment by mimarz** [comment]
Finished!
