### ISSUE TITLE
Figma Community Changelog

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1299]
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/2086
- [ ] https://github.com/digdir/designsystemet/issues/1869
- [ ] https://github.com/digdir/designsystemet/issues/1582
- [ ] https://github.com/digdir/designsystemet/issues/1474
- [ ] https://github.com/digdir/designsystem/issues/1301
- [ ] https://github.com/digdir/designsystem/issues/1300
- [ ] https://github.com/digdir/designsystemet/issues/2174
```

**Comment by mimarz** [comment]
@mrosvik will move this to wiki

**Comment by mrosvik** [comment]
See https://github.com/digdir/designsystemet/wiki/Figma-Community-Changelog
