### ISSUE TITLE
New component: ErrorSummary

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1317]
## Related information and insight
- GovUK: https://design-system.service.gov.uk/components/error-summary/
- Aksel: https://aksel.nav.no/komponenter/core/errorsummary
- Vi har vurderert om `alert`-komponenten kan brukes, men konkludert med at `ErrorSummary` bør fremstilles mildere enn `alert`. 

## Specification and requirements
- ...
-
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/1318
- [ ] https://github.com/digdir/designsystem/issues/1319
- [ ] https://github.com/digdir/designsystem/issues/1320
- [ ] WCAG-test
- [ ] https://github.com/digdir/designsystemet/issues/1411
```
