### ISSUE TITLE
Change `icon` & deprecate `iconPlacement` props for `Button` & `Tabs.Tab`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1333]
After a short meeting on 5 jan, we decided to change `icon` & remove `iconPlacement` from our react components (`Button` & `Tabs.Tab`) to provide better flexibility in using icons inside our components. 

This will also fix other issues such as:
- This will work better with polymorphic support using [Slot](https://www.radix-ui.com/primitives/docs/utilities/slot) as we have issues using `as` and callbacks. #1124 
- Future RSC support means we want to avoid using props for rendering components as it will break the possibility for server components inside client components. 

The property `icon` will be changed to a `boolean` to toggle when the button is used with a single icon and no text. 

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/1338
- [ ] https://github.com/digdir/designsystemet/issues/1412
- [ ] https://github.com/digdir/designsystemet/issues/1417
- [ ] https://github.com/digdir/designsystemet/issues/1334
```

**Comment by Barsnes** [comment]
Closing this issue as all tasks has been completed
