### ISSUE TITLE
Add font-weight to paragraph component in Figma

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1346]
NB: We ended up overwriting the typography token with another font weight. Seems to work with different viewports

```[tasklist]
### Tasks
- [ ] Remove `font-weight` from typography-tokens on `Paragraph` and `Label`
- [ ] Add font-weight tokens to semantic set in tokens.
- [ ] Create variants of paragraph and label in Figma and connect them to correct font-weight tokens.
- [ ] React: Add new `font-weight` to the `Paragraph` and `Label` component
- [ ] Update token script to handle decoupled `font-weight` from typography token
```

**Comment by mimarz** [comment]
@mrosvik will have a look at this

**Comment by Febakke** [comment]
Closing this. Only change is a new font-weight to the typography component in Figma
