### ISSUE TITLE
Add example cases to components

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1348]
## Examples in components

```[tasklist]
### Tasks
- [x] Add example to Accordion (Figma)
- [x] Add example to Alert (Figma)
- [x] Add example to Button (Figma)
- [x] Add example to Button with only icon (Figma)
- [x] Add example to Checkbox
- [x] Add example to Chip
- [x] Add example to Card
- [x] Add example to Combobox with chips inside
- [x] Add example to Combobox with chips outside
- [x] Add example to DropdownMenu
- [x] Add example to ErrorSummary
- [x] Add example to Helptext
- [x] Add example to Link
- [x] Add example to List
- [x] Add example to Loaders
- [x] Add example to Modal
- [x] Add example to Pagination
- [x] Add example to Popover
- [x] Add example to Radio
- [x] Add example to Search
- [x] Add example to SkipLink
- [x] Add example to Switch
- [x] Add example to Table
- [x] Add example to Tag
- [x] Add example to TextArea
- [x] Add example to TextField
- [x] Add example to ToggleGroup
- [x] Add example to Tooltip
- [x] Add example to Typography
```

**Comment by mimarz** [comment]
Moved back to todo for when someone else has the time to continue this issue.
