### ISSUE TITLE
Strategi og OKR-samling 22-23.jan

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1379]
```[tasklist]
### Tasks
- [x] Invitere til samling
- [x] Planlegge samling, lage Miro-board og opplegg
- [x] Gjennomføre samling 22.-23.januar
- [ ] Sammenstille
```

**Comment by mrosvik** [comment]
Sammenstillingen vil jobbes videre med i Produktstrategien.
