### ISSUE TITLE
Combobox: Loading icon

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1382]
```[tasklist]
### Tasks
- [x] Sketch component in Figma
- [x] Add component to "Felles componenter"
- [ ] https://github.com/digdir/designsystemet/issues/1447
```

**Comment by Edavda** [comment]
Initial sketches can be found [here](https://www.figma.com/file/V4dzf3m1sapmU048OQnu7L/Arbeidsomr%C3%A5de%3A-Felles-komponenter?type=design&node-id=3105-44383&mode=design)

**Comment by mrosvik** [comment]
@Febakke will move the loading icon example into "Felles komponenter"

**Comment by Febakke** [comment]
Moved to "felles komponenter"

**Comment by Barsnes** [comment]
Closing as finished after merge and release 23.02.2024
