### ISSUE TITLE
Blog post about V1

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1429]
```[tasklist]
### Tasks
- [x] Make small film clips of new features (Create example of video)
- [x] With big releases, create a blog post explaining whats done and what we will be working with. (Create example of blog post)
- [x] Blog post about V1 Release candidate
- [x] Blog post about postpone V1
- [x] Blog post about V1 launching
```
