### ISSUE TITLE
Merch

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1430]
We need some merch for Designsystemet that can be shared at conferences, stands, etc.

- Stickers for laptops is suggested
- We should have a special shiny edition that only contributors will receive ✨🦄

```[tasklist]
### Tasks
- [x] Clarify costs and financing
- [x] Clarify with KOM
- [ ] Sticker for laptops
- [ ] Sticker - shiny edition for contributors
- [ ] Liten refleks til å ha på sekk/jakke?
- [ ] Strap refleks
- [ ] Sweather for stands
- [ ] Roll-up for stands
```
```[tasklist]
### Tasks
```

**Comment by Barsnes** [comment]
I would suggest reflective things, which are super usefule! 😄 
ex:
![Image](https://github.com/user-attachments/assets/436b04b0-b0d6-4aef-a5ea-626dde5e7fad)
