### ISSUE TITLE
Theme builder

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1431]
```[tasklist]
### Tasks for Beta version (29. mai)
- [x] Bachelor's thesis with interviews and user testing of prototype
- [ ] https://github.com/digdir/designsystemet/issues/1036
- [ ] #1377
- [ ] https://github.com/digdir/designsystemet/issues/1843
- [ ] https://github.com/digdir/designsystemet/issues/2044
- [ ] https://github.com/digdir/designsystemet/issues/2045
- [ ] The switch button checkmark has wrong color
```

```[tasklist]
### Tasks for later versions
- [ ] Make use of Brreg Contrast checker in the theme builder https://contrast.brreg.no/
```

**Comment by mimarz** [comment]
We have built a theme-builder now and will handle future enchancements with new epic, labels and milestones.
