### ISSUE TITLE
🧭  Roadmap 2024

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1435]
Previous roadmaps:
- [Roadmap 2023](https://github.com/digdir/designsystemet/issues/468)

## Q1-Q2 2024
**Ferdigstille V1**

```[tasklist]
### Tasks
- [x] Ferdigstille 30 komponenter som skal være del av V1
- [x] Bytte til en statisk typografisk skala som default
- [x] Endringer på noen tokens og oppdatering på React komponenter iht. tokens-endringene.
- [ ] #918
```

----

### Planlagte fremtidige løsninger

![Frame 1258](https://github.com/digdir/designsystemet/assets/1464915/7aa34a1a-8554-4eb1-a0fa-51f3c8eea376)

## Q3-Q4 2024
- Utvikle flere komponenter, forbedre retningslinjer, eksempler og dokumentasjon. 
- CSS-bibliotek
- Dark Mode
- Temavelger

----

## Videre arbeid 

**✧ Etablere felles mønstre**
- Koordinere arbeidsgruppe som utarbeider felles mønstre på tvers av flere etater. (Arbeidsgruppe er igangsatt for 2024). 

**✧ Utvide samarbeidet**
- Jobbe for et tverretatlig designsystem-team gjennom ordnede rammer i det offentlige

**✧ Brukertilfredshet**
- Jobbe for bedre utvikler- og designer-opplevelse
- Gjennomføre jevnlige undersøkelser om bruk og user satisfaction

**✧ Utvide til mer enn et komponentbibliotek - et felles hjem for god praksis.**
- Vi skal lage gode tjenesteutviklings-guider
- Lage guider og andre hjelpemidler slik at teamene får ekstra støtte til å lage tilgjengelige løsninger, samt bruke komponentene til det de er ment til.
- Tilby retningslinjer for klarspråk og brukerdialog
- Lage en base for deling av innsiktsarbeid, og fra hver komponent og mønster skal det finnes lenke til relevant innsiktsarbeid.
- Retningslinjer og eksempler for bruk av animasjon
- Retningslinjer og eksempler for bruk av datavisualisering

**✧ Forvaltning og forbedringer**
- Vi skal jobbe med å holde dokumentasjonen og eksemplene oppdatert til en hver tid og tilby relevante eksempler for hvordan lage inkluderende tjenester. 
- Vi skal samle inn nye behov som går på tvers og tilby komponenter og mønstre for disse.

**Comment by mrosvik** [comment]
Closing this as the Roadmap is now defined in: https://github.com/orgs/digdir/projects/3/views/30 

Milestones: https://github.com/orgs/digdir/projects/3/views/30
