### ISSUE TITLE
Avoid using xxxlarge naming convention on our tokens

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1451]
We use xxxlarge syntax on some of our tokens. We should use standard way of doing this that has better readablity.
Example:
`xlarge- 2xlarge - 3xlarge - 4xlarge`

- Typography heading
![Image](https://github.com/digdir/designsystemet/assets/1464915/5397c564-2e8b-4e5d-972b-d42da9cb3fac)

- Border-radius
![Image](https://github.com/digdir/designsystemet/assets/1464915/9979437d-1953-482b-8e93-57c0e3058685)

```[tasklist]
### Tasks
- [x] Decide on new naming
- [x] Change token xxsmall for heading to 2xsmall
- [x] Announce breaking change
```

**Comment by mrosvik** [comment]
We should also consider `sm` - `md` - `lg`

**Comment by mrosvik** [comment]
Codemod?

**Comment by Barsnes** [comment]
Suggestion:
Use `xs`, `sm`, `md`, `lg`, `xl` and for smaller or bigger sizes just prefix with a number. Ex.: `2xs` and `2xl`

This is a more common pattern, used by [tailwind](https://tailwindcss.com/docs/theme), [chakra](https://chakra-ui.com/docs/styled-system/style-props#layout-width-and-height), and others
