### ISSUE TITLE
Figma Community 1.0.4-Beta

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1474]
Changelog and tasks to fix in our Community file

```[tasklist]
### Tasks
- [x] Linked color variables
- [x] Linked spacing variables
- [x] Linked sizing variables
- [x] Fix spacing on focus button (medium)
- [x] Fixed left side read-only labels on Switch
- [x] Added size 2xlarge and 3xlarge to 'Header'
- [x] Fix ghost variables on brand example
- [x] Fix ghost variables on Accordion
```

**Comment by mrosvik** [comment]
https://www.figma.com/community/file/1322138390374166141/designsystemet-core-ui-kit
