### ISSUE TITLE
Improved component documentation and guidelines

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1479]
- [x] https://github.com/digdir/designsystemet/issues/506 - Gjennomgått 08.05.2025
- [x] https://github.com/digdir/designsystemet/issues/1097 - Gjennomgått 08.05.2025
- [x] Badge - Gjennomgått 08.05.2025
- [x] https://github.com/digdir/designsystemet/issues/1103 - Gjennomgått 08.05.2025
- [x] https://github.com/digdir/designsystemet/issues/1480 - Gjennomgått 12.05.2025
- [x] https://github.com/digdir/designsystemet/issues/573 - Gjennomgått 13.05.2025
- [x] https://github.com/digdir/designsystemet/issues/65 - Gjennomgått 13.05.2025
- [x] https://github.com/digdir/designsystemet/issues/51 - Gjennomgått 14.05.2025
- [x] Details - Gjennomgått 14.05.2025
- [x] https://github.com/digdir/designsystemet/issues/586 - Gjennomgått 15.05.2025
- [x] Divider  - Gjennomgått 15.05.2025
- [x] https://github.com/digdir/designsystemet/issues/1482
- [x] https://github.com/digdir/designsystemet/issues/1319 - Gjennomgått 20.05.2025
- [x] Field - Gjennomgått 20.05.2025
- [x] https://github.com/digdir/designsystemet/issues/1496 - Gjennomgått 16.05.2025
- [x] Input - Gjennomgått 02.06.2025
- [x] https://github.com/digdir/designsystemet/issues/1484 - Gjennomgått 07.08.2025
- [x] https://github.com/digdir/designsystemet/issues/1486 - Gjennomgått 07.08.2025
- [x] https://github.com/digdir/designsystemet/issues/1487 - Gjennomgått 13.08.2025
- [x] https://github.com/digdir/designsystemet/issues/540  - Gjennomgått 16.05.2025
- [x] https://github.com/digdir/designsystemet/issues/1489  - Gjennomgått 15.08.2025
- [x] https://github.com/digdir/designsystemet/issues/523 - Gjennomgått 02.06.2025
- [x] https://github.com/digdir/designsystemet/issues/1490 - Gjennomgått 16.08.2025
- [x] https://github.com/digdir/designsystemet/issues/1497 - Gjennomgått 02.06.2025
- [x] https://github.com/digdir/designsystemet/issues/1054 - Gjennomgått 20.08.2025
- [x] https://github.com/digdir/designsystemet/issues/645 - Gjennomgått 04.08.2025
- [x] https://github.com/digdir/designsystemet/issues/1343 - Gjennomgått 03.06.2025
- [x] https://github.com/digdir/designsystemet/issues/1491 - Gjennomgått 16.08.2025
- [x] https://github.com/digdir/designsystemet/issues/490 - - Gjennomgått 06.08.2025
- [x] https://github.com/digdir/designsystemet/issues/1492 - Gjennomgått 02.06.2025
- [x] https://github.com/digdir/designsystemet/issues/1493 - Gjennomgått 02.06.2025
- [x] https://github.com/digdir/designsystemet/issues/806 - Gjennomgått 20.08.2025
- [x] https://github.com/digdir/designsystemet/issues/1494 - Gjennomgått 04.08.2025
- [x] https://github.com/digdir/designsystemet/issues/1495 - Gjennomgått 07.08.2025

**Comment by Barsnes** [comment]
I think we can drop `Suggestion`, or at least don't go as in-depth as the other docs. 
The component is still in experimental, and I think documenting it should be the last thing we do once we want to remove it from experimental

**Comment by mrosvik** [comment]
We have reviewed the documentation for all components (except Suggestion, since it is still experimental). With that, we are closing this epic.
