### ISSUE TITLE
Storefront adjustments for v1

### ISSUE THREAD

**Issue by Thunear** [digdir/designsystemet#1517]
A redesign of the Storefront for v1.

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/1423
- [ ] https://github.com/digdir/designsystemet/issues/1518
- [ ] https://github.com/digdir/designsystemet/issues/1138
- [ ] https://github.com/digdir/designsystemet/issues/1525
- [ ] https://github.com/digdir/designsystemet/issues/1526
- [ ] https://github.com/digdir/designsystemet/issues/1554
- [ ] https://github.com/digdir/designsystemet/issues/1657
- [ ] https://github.com/digdir/designsystemet/issues/1670
```
