### ISSUE TITLE
Figma community 1.0.5

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1582]
Document of all changes done to our UI kit in Figma
```[tasklist]
### Changelog
- [ ] https://github.com/digdir/designsystemet/issues/1541
- [ ] https://github.com/digdir/designsystemet/issues/1565
- [x] Swapped 10px padding for spacing-2 token inside elements on combobox
- [ ] https://github.com/digdir/designsystemet/issues/1533
- [ ] https://github.com/digdir/designsystemet/issues/1588
- [x] Fixed border-radius on combobox focus indicator
- [x] Reset all changes to "Label with description" on TextField Small, because the label where set to 21px height instead of 20px.
- [x] Reset all changes to "Label with description" on TextField Medium, because the label where set to 24px height instead of 23px.
- [x] Radio Large: Change gap between box and text from 9px to 12px (only large)
- [x] Checkbox Large: Change gap between box and text from 9px to 12px (only large)
- [x] Switch Large: Change gap between box and text from 9px to 12px (only large)
- [x] Button group medium: Change gap from 12px to 16px
- [x] Button group large: Change gap from 12px to 20px
- [x] Added better example for Accordion with full border radius
- [x] Fixed wrong opacity on disabled search
- [ ] https://github.com/digdir/designsystemet/issues/1385
- [x] Chip is improved with better icon sizing, spacing and colors.
- [x] Changed gap between small radio, checkbox to 12px (the group component)
- [x] Changed gap between medium radio, checkbox to 16px (the group component)
- [x] Changed gap between large radio, checkbox to 20px (the group component)
- [x] Updated all links to storybook documentation and component guidelines
- [x] Fix sizing issue with Pagination
- [x] Fix spacing issue with Popover/Helptext
- [ ] https://github.com/digdir/designsystemet/issues/1772
- [x] Created Focus indicator base component (For the new focus style)
- [x] Remove focus variants
- [ ] https://github.com/digdir/designsystemet/issues/1769
- [ ] https://github.com/digdir/designsystemet/issues/1444
- [ ] https://github.com/digdir/designsystemet/issues/1585
```

**Comment by mrosvik** [comment]
This version was published to community 23.04.24.
