### ISSUE TITLE
New sizing and spacing for our components

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1583]
Vi (@mrosvik og @Thuneer) har sett på størrelsene med den nye statiske skalaen ifb. #1444 , og kommet frem til at `button`, `textfield` og `combobox`, `Search`, `NativeSelect` justeres til:

- Small: `Sizing-10` (40px) , 16px fontsize
- Medium: `Sizing-12` (48px), 18px fontsize
- Large: `Sizing-14` (56px), 21px fontsize

Dette betyr at vi må sette nye sizing og spacing tokens på `Button`, `TextField` og `Combobox`, men det bør ikke være så stor jobb. 

![image](https://github.com/digdir/designsystemet/assets/1464915/23a05cd0-cb1f-4f97-b0e8-d4cb7bbefcef)

`Checkbox` og `Radio` justeres lit fordi boksene ved siden av teksten er litt for store slik det er i dag:
- Small: `Sizing-5` (20px) , 16px fontsize
- Medium: `Sizing-6` (24px), 18px fontsize
- Large: `Sizing-7` (28px), 21px fontsize

Dette gjøres for å:
- Oppnå god balanse mellom fontsize og spacing i komponentene
- At default (medium) oppnår kravet for 44px 

Bilde som viser bruken av `Small`, `Medium` og `Large`:

![Frame 188](https://github.com/digdir/designsystemet/assets/13560642/4559e571-4a6c-4546-a7d4-866f892a3644)

Bilde som viser hvordan ulike størrelser av komponenter kan brukes sammen:

![Frame 183](https://github.com/digdir/designsystemet/assets/13560642/444d9137-b29d-4daf-a29b-8a7d826c5724)

```[tasklist]
### Tasks
- [x] Define new sizing scale
- [ ] https://github.com/digdir/designsystemet/issues/1605
- [ ] https://github.com/digdir/designsystemet/issues/1780
- [ ] https://github.com/digdir/designsystemet/issues/1585
- [ ] https://github.com/digdir/designsystemet/issues/1586
- [ ] https://github.com/digdir/designsystemet/issues/1444
- [ ] https://github.com/digdir/designsystemet/issues/1563
- [ ] https://github.com/digdir/designsystemet/issues/1478
- [ ] https://github.com/digdir/designsystemet/issues/1621
```

**Comment by mrosvik** [comment]
Relevant: https://github.com/digdir/designsystemet/issues/1712

**Comment by mimarz** [comment]
Previous feedback from @Thuneer 

> chip - 28, 32, 36 høyde
> tag - 28, 32, 36 høyde
> search - 4px meir padding left på medium og large
> switch- 24x44, 28x52, 32x60
> combobox - 40, 48, 56 høyde
> 
> Ligger på "All components" sida i denne branchen: [https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/branch/jfNqXceGd2YqXZGuOStjb3/Des[…]e=design&node-id=31468%3A5491&mode=design&t=eaclWPJWj4i52z7z-1](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/branch/jfNqXceGd2YqXZGuOStjb3/Designsystemet---Core-UI-Kit?type=design&node-id=31468%3A5491&mode=design&t=eaclWPJWj4i52z7z-1)

**Comment by mimarz** [comment]
@Thuneer The "thumb" on `Switch` is not entirely on level 4 scaling as we are using [scale](https://developer.mozilla.org/en-US/docs/Web/CSS/scale) to properly scale it on all sizes and zoom levels. Suggest we have a look at it when your back :)
