### ISSUE TITLE
Design 3 websites to test components and sizes

### ISSUE THREAD

**Issue by Thunear** [digdir/designsystemet#1593]
**Internal admin application:**
* Compact design
* 16px base font

**External website with selv-service portal**
* More spacious design
* 18px base font

**External website that showcases a product or service:**
* Very spacious design
* 18px base font

```[tasklist]
### Tasks
- [x] Internal admin application
- [x] External website with selv-service portal
- [x] External website that showcases a product or service
```

![Image](https://github.com/user-attachments/assets/e3471c1f-6d1f-450c-81b3-997b199b8944)
