### ISSUE TITLE
Docs: Update info about Sizing and Spacing

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1598]
![Image](https://github.com/digdir/designsystemet/assets/1464915/6226a928-de7e-4e63-9a7e-6e8b1cc3fc34)

```[tasklist]
### Tasks
- [x] Combine Sizes and Spacing into one page
- [ ] Rewrite text about sizing
- [x] Remove the part about component-mode-heigh since it is not in use anymore
- [x] Title could be "Størrelser og avstander"
```
