### ISSUE TITLE
Storefront: Create components page

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystemet#1657]
New `/components` page that shows a list of all the components with a Card design.

```[tasklist]
### Tasks
- [x] Design the layout in Figma
- [ ] https://github.com/digdir/designsystemet/issues/1662
- [x] Decide on a ingress text
```

**Comment by mrosvik** [comment]
@mrosvik will add suggestion for ingress.

**Comment by Barsnes** [comment]
@Thuneer Should this be closed?

**Comment by Thuneer** [comment]
This is done so closing this issue.
