### ISSUE TITLE
Active color missing on neutral and subtle link card

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1711]
Seems like we missed having an active color on our neutral and subtle variants of `link card`. Active is used on click to indicate that you are currently clicking on the card.
<img width="927" alt="Skjermbilde 2024-03-18 kl  15 59 56" src="https://github.com/digdir/designsystemet/assets/33222679/79b6635c-22ec-4b58-9867-04907e21034a">

I think this happened because we lack a active neutral color. We need to add or find a color that can be used for cases like this.
<img width="240" alt="Skjermbilde 2024-03-18 kl  16 00 14" src="https://github.com/digdir/designsystemet/assets/33222679/171c1a2d-7147-4f4e-98d0-af27fd5300eb">

Our react component of neutral and subtle becomes white on click (active)

```[tasklist]
### Tasks
- [ ] Add new color tokens
- [ ] https://github.com/digdir/designsystemet/issues/1753
- [ ] Fix in react
```

**Comment by Barsnes** [comment]
Is this still an issue? Seems to be fixed in the `next` version: https://next.storybook.designsystemet.no/?path=/story/komponenter-card--link-card

**Comment by Febakke** [comment]
@Barsnes Yes, fixed in Figma as well. Closing this as finished.
