### ISSUE TITLE
Change focus indicator

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1776]
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/1409
- [x] Change in react
- [x] Add focus indicator explaination in Figma
- [ ] https://github.com/digdir/designsystemet/issues/1777
- [ ] https://github.com/digdir/designsystemet/issues/2080
```
