### ISSUE TITLE
New component: Badge

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#1816]
### Discussed in https://github.com/digdir/designsystemet/discussions/1815

<sup>Originally posted by **mimarz** March 14, 2024</sup>
Component requested by Dialogporten.

The need is for a component to indicate a number of notifications using numerical values that can be attached or inlined with other elements.

Things to consider:
- Need to review this against usage with `Tag`
- Is this just `Tag` with rounded borders or a separate component? Mixed definitions out here

Examples
- https://atlassian.design/components/badge/examples
- https://orbit.kiwi/components/information/notificationbadge/

```[tasklist]
### Tasks
- [x] Badge: Write about specification, requirements and scope in this issue
- [ ] https://github.com/digdir/designsystemet/issues/2210
- [x] Badge: Write guidelines for usage
- [ ] https://github.com/digdir/designsystemet/issues/2211
```

**Comment by Barsnes** [comment]
From Slack, this is the difference between Chip, Badge and Tag:
**Chip**: Interaktiv komponent
**Badge**: Ikkje interaktiv komponent som viser status med eller uten tall
**Tag**: Ikkje interaktiv komponent for å merke innhold med kategori/emne (kategori kan være status i teksformat)
