### ISSUE TITLE
Mainquest: Move css-modules to plain css

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1846]
Sidequest whenever we have some spare time or we are in one of our components that has css defined as a `*.module.css` move it to separate `.css` file if it doesn't require to much work. 

Actions
1. Move `module.css` file to `packages/css` and rename it to component name in lowercase.
   1. `Button.module.css` -> `button.css`
   1.  **_Its important you move and rename the file to retain git file history_**.
2. Rename classes to follow a [bem naming](https://getbem.com/naming/). 
   1. Prefix classes with `fds-`
   1. Prefix component css variables with `--fds-[component-name]`, like `--fds-button-`
3. Update React component to use new classnames instead of css-module object
   1. Replace use of `clsx` with [clsx/lite](https://github.com/lukeed/clsx?tab=readme-ov-file#clsxlite), i.e. don't use objects for classname string building
2. Run `build` to generate new `react-css-modules.css` file (to remove old css modules for component)

Notes
- One PR per component with title `refactor("component names"):`
- Add #1846 in the top of PR description just to get a mention to this issue
- Save `Combobox` for last due to lots of planned changes: #1771
- Expect to need to refactor some css classes to support string manipulation according to props.
- Example: [Alert](https://github.com/digdir/designsystemet/blob/main/packages/react/src/components/Alert/Alert.tsx) and [alert.css](https://github.com/digdir/designsystemet/blob/main/packages/css/alert.css)
- Components with multiple sub-component and css should be merged into one css file and layer (accordion, dropdownmenu, list, etc)
- If possible, avoid component element structure dictating css structure
- Inspiration for naming:
  - https://punkt.oslo.kommune.no/latest/komponenter/
  - https://design-system.service.gov.uk/components
  - https://designsystem.dk/kode/komponenter

Components:
```[tasklist]
### Tasks
- [x] Accordion
- [x] Box
- [x] Card
- [x] Chip
- [x] Divider
- [x] DropdownMenu
- [x] ErrorSummary
- [x] Checkbox
- [x] Combobox
- [x] Fieldset
- [x] NativeSelect
- [x] Radio
- [x] Search
- [x] Switch
- [x] Textarea
- [x] Textfield
- [x] HelpText
- [x] Link
- [x] List
- [x] Modal
- [x] Pagination
- [x] Popover
- [x] Skeleton
- [x] Spinner
- [x] Table
- [x] Tabs
- [x] Tag
- [x] ToggleGroup
- [x] Tooltip
- [x] ErrorMessage
- [x] Heading
- [x] Label
- [x] Paragraph
```

**Comment by mimarz** [comment]
Do we want to make a separate issue for each component or just take it as we go? @Barsnes

**Comment by poi33** [comment]
I'll try to take a crack at this quest as soon as I have some time 🗡️🛡️

**Comment by Barsnes** [comment]
> Do we want to make a separate issue for each component or just take it as we go? @Barsnes

I think making a separate issue for each component is a bit overkill. 
I suggest we do it as we go, and if we forget, it's no big deal.

**Comment by mimarz** [comment]
> > Do we want to make a separate issue for each component or just take it as we go? @Barsnes
> 
> I think making a separate issue for each component is a bit overkill. I suggest we do it as we go, and if we forget, it's no big deal.

Yeah, thinking the same, its just internal refactors anyways.

**Comment by Barsnes** [comment]
After this we can also remove `postcss-layers.js` - which is then not needed anymore

**Comment by poi33** [comment]
Adding a list for to keep track of all the module files:

- [ ] Accordion\Accordion.module.css
- [ ] Box\Box.module.css
- [ ] Card\Card.module.css
- [ ] Chip\Chip.module.css
- [ ] Divider\Divider.module.css
- [ ] DropdownMenu\DropdownMenu.module.css
- [ ] DropdownMenu\DropdownMenuGroup\DropdownMenuGroup.module.css
- [ ] DropdownMenu\DropdownMenuItem\DropdownMenuItem.module.css
- [ ] ErrorSummary\ErrorSummary.module.css
- [ ] form\Checkbox\Checkbox.module.css
- [ ] form\Combobox\Combobox.module.css
- [ ] form\Combobox\Custom\Custom.module.css
- [ ] form\Combobox\Empty\Empty.module.css
- [ ] form\Combobox\Option\Option.module.css
- [ ] form\Combobox\Option\Description\Description.module.css
- [ ] form\Fieldset\Fieldset.module.css
- [ ] form\NativeSelect\NativeSelect.module.css
- [ ] form\Radio\Radio.module.css
- [ ] form\Radio\Group\Group.module.css
- [ ] form\Search\Search.module.css
- [ ] form\Switch\Switch.module.css
- [ ] form\Textarea\Textarea.module.css
- [ ] form\Textfield\Textfield.module.css
- [ ] HelpText\HelpText.module.css
- [ ] Link\Link.module.css
- [ ] List\List.module.css
- [ ] Modal\Modal.module.css
- [ ] Modal\ModalContent\ModalContent.module.css
- [ ] Modal\ModalFooter\ModalFooter.module.css
- [ ] Modal\ModalHeader\ModalHeader.module.css
- [ ] Pagination\Pagination.module.css
- [ ] Popover\Popover.module.css
- [ ] Skeleton\Skeleton.module.css
- [ ] Spinner\Spinner.module.css
- [ ] Table\Table.module.css
- [ ] Tabs\Tab\Tab.module.css
- [ ] Tabs\TabContent\TabContent.module.css
- [ ] Tabs\TabList\TabList.module.css
- [ ] Tag\Tag.module.css
- [ ] ToggleGroup\ToggleGroup.module.css
- [ ] ToggleGroup\ToggleGroupItem\ToggleGroupItem.module.css
- [ ] Tooltip\Tooltip.module.css
- [ ] Typography\ErrorMessage\ErrorMessage.module.css
- [ ] Typography\Heading\Heading.module.css
- [ ] Typography\Label\Label.module.css
- [ ] Typography\Paragraph\Paragraph.module.css

**Comment by mimarz** [comment]
Nice! @poi33 I updated the description with tasklist for each component we can check off when completed:)

**Comment by poi33** [comment]
Much easier👍 Thanks

**Comment by mimarz** [comment]
> Much easier👍 Thanks

No problem! Are you allowed to check of the tasks or create issues from them? 

![image](https://github.com/digdir/designsystemet/assets/1070981/81f67b91-e0dc-4c86-80e0-252672f4ee6e)

**Comment by poi33** [comment]
No 😿, but one of you need to review the pull request for it and can mark it done that way. 🤷

**Comment by mimarz** [comment]
We have prioritised this to "now", due to planned changes in [#1727](https://github.com/digdir/designsystemet/issues/1727) which will result in a lot of changes for our css.

**Comment by mimarz** [comment]
Finished! 

Great work! @poi33 @Barsnes 

![success-great-job](https://github.com/digdir/designsystemet/assets/1070981/a851a4cc-b7ab-4bb5-98ca-3e9757bdc8d6)
