### ISSUE TITLE
Figma Community V1 Release Canditate - 1 (May 2024)

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#1869]
Document of all changes done to our UI kit in Figma in this version

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/1708
- [x] Removed extra label on small read only switch
- [x] Tags will now fall down when taking all the width inside `cards`
- [x] Texts inside `popover` now use `text/neutral/default`
- [x] Removed unused `right text` prop on `card`
- [x] Texts inside `textarea` now use `text/neutral/default`
- [x] Remove heading 3xl from variants (not in use anymore)
- [ ] https://github.com/digdir/designsystemet/issues/1245
- [x] Add new focus overview with descriptions
- [x] Renamed sizes to sm, md, lg, xl
- [x] Updated all components with new tokens from the new color system
- [ ] https://github.com/digdir/designsystemet/issues/2041
```

**Comment by mrosvik** [comment]
Published to Community 28.05.2024
