### ISSUE TITLE
CSS discrepancies

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#1952]
Issue where we scribble down notes and things we discovered during #1846 we should look into.

```[tasklist]
### Tasks
- [ ] Maybe avoid classes for readonly and disabled and rely on native selectors instead.
- [ ] We should probably add css classes to our components for users to be able to target elements
- [ ] tooltip: Has no styling for content arrow. This is provided from floating-ui
- [ ] chip: clean up css variables
- [ ] Try to use aria-attributes (that needs to be set) to style as much as possible
```

**Comment by eirikbacker** [comment]
Will be solved by #2295
