### ISSUE TITLE
Migrate Figma to tokens v2

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2041]
When marking a component finished, you should make sure the old "Brand" set is gone from the options.

```[tasklist]
### Tasks
- [x] Scopes
- [x] Test: 1. Change some variables. 2. Create a second theme. 3. Create variables. 4. Check if the variables created in step 1 is linked correct.
- [x] The overview-page
- [x] Focus
- [x] All components:
- [x] Accordion
- [x] Alert
- [x] Button
- [x] Button sliter på darkmode.  Text-default på secondary og tertiary button sidan desse er mot bakgrunnsfargen og surface. Så blir det contrast-1 på primary siden denne har base-default som bakgrunnsfarge.
- [x] Card
- [x] LinkCard
- [x] Checkbox
- [x] Chip
- [x] Combobox
- [x] DropdownMenu
- [x] ErrorSummary - Denne ble slettet og laget på nytt pga av feil i Liste-komponenten
- [x] Helptext
- [x] Link
- [x] Link is missing purple
- [x] Link: What color should Pressed state be? text-default, with box on active
- [x] List
- [x] Loader
- [x] Modal - Denne ble slettet og laget på nytt pga av gamle knappekomponenter
- [x] Pagination - Denne ble slettet og laget på nytt pga av gamle knappekomponenter
- [x] Popover (Lasse) Denne ble slettet og laget på nytt pga av gamle knappekomponenter
- [x] Radio
- [x] Search
- [x] SkipLink
- [x] Switch
- [x] Table
- [x] Tabs
- [x] Tag
- [x] Textarea
- [x] TextField
- [x] ToggleGroup - Denne ble slettet og laget på nytt pga av gamle knappekomponenter
- [x] Tooltip
- [x] Typography
- [x] Helptext
- [x] Modal
```
