### ISSUE TITLE
Migration bugs V1 RC - Figma

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2077]
This is a collection of bugs that should be fixed in RC1. 
```[tasklist]
### Tasks
- [ ] Existing color overview is outdated and deleted. New color page should be made with new colors
- [ ] The overview page still has some ghost variables
- [ ] Accordion må bli bygget opp uten opacity. Dele opp base komponent i 3 brand-farger, der line har brandfarge i stedet for hvit. Vi kan gjøre dette etter RC1.
- [ ] Dropdown: What to do with shadows on darkmode?
- [ ] Button danger er ikke kontrastgodkjent. @thuneer justerer dette.
- [ ] ToggleGroup: There should be a variant of ToggleGroup with onlyIcon button
```

**Comment by mrosvik** [comment]
Duplicate of #2086
