### ISSUE TITLE
Figma community V1 Release candidate - 2

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2086]
Changelog for Figma

```[tasklist]
### Tasks
- [x] Changed token on checked radiobutton `accent-border-strong`-> `accent-base-default`
- [x] Added description to our focuspage
- [x] Added a color page
- [x] The overview page still has some ghost variables
- [x] Oppdaterte link card brand variantene til border-default i stedet for border-subtle
- [x] Changed textsize on small textfield 15.5 -> 15
- [x] Added dark-mode example for ToggleGroup
- [x] Bedre kontrast på Button danger
- [x] Wrong color on checkbox label, fixed back to `neutral-text-default`
- [x] Alert icon should use text-subtle instead of base-default
- [x] Fixed wrong variant names on linkCard
- [x] Mobile examples has some ghost variables
- [ ] https://github.com/digdir/designsystemet/issues/2088
- [ ] https://github.com/digdir/designsystemet/issues/2104
- [ ] https://github.com/digdir/designsystemet/issues/2102
- [ ] https://github.com/digdir/designsystemet/issues/2098
- [x] https://github.com/digdir/designsystemet/issues/2145
- [x] Update Pagination, Modal, SkipLink, Card, Popover with the new button component
- [x] Update all examples with new button component
- [x] https://github.com/digdir/designsystemet/issues/2146
- [ ] https://github.com/digdir/designsystemet/issues/2118
- [ ] https://github.com/digdir/designsystemet/issues/2142
- [ ] https://github.com/digdir/designsystemet/issues/2079
- [ ] https://github.com/digdir/designsystemet/issues/2111
- [ ] https://github.com/digdir/designsystemet/issues/1777
- [ ] https://github.com/digdir/designsystemet/issues/2103
- [ ] https://github.com/digdir/designsystemet/issues/2116
```
