### ISSUE TITLE
React: Table improvements

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#209]
Issues related to improving and cleaning up the react components for tables. `Table` & `ResponsiveTable`

```[tasklist]
### Tasks
- [ ] Remove the uses of [any](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any)
- [ ] Add JSDoc to Table components
- [ ] Do improvements in Table component (marked with TODOs)
- [ ] Decide if `Table` should expose sub-components on parent for ease of use
- [ ] Fix Table storybook stories
```

**Comment by mimarz** [comment]
No longer relevant as we will develop a new `Table` component
