### ISSUE TITLE
Figma community V1 Release candidate - 3

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#2174]
Changelog for Figma 

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/2182
- [ ] https://github.com/digdir/designsystemet/issues/2183
- [x] Add textstyle to paragraph in modal
- [ ] https://github.com/digdir/designsystemet/issues/2210
- [x] Modal close-icon did not use variable
- [x] Fixed broken variabels on radio component label
- [x] Added badge to dropdown menu
- [x] Added sizing variables to spinner and changed to new namin
- [ ] https://github.com/digdir/designsystemet/issues/2282
- [x] Divider do not scale with card
- [x] Remove card instance (example) that has been accidently made into a component
- [x] Updated Helptext after changes to the react component
- [x] Renamed `dropdownMenu`-> `dropdown`
- [x] Renamed `error-message` -> `validationMessage`
- [x] Remove `errorSummary` example that has been accidently made into a component
- [x] Remove copy of core component of `linkCar` header
- [ ] https://github.com/digdir/designsystemet/issues/2321
- [ ] https://github.com/digdir/designsystemet/issues/2309
- [ ] https://github.com/digdir/designsystemet/issues/2407
- [x] Radio and checkbox should use background-default (not contrast-default)
- [x] Fixed scaling on focus indicator on text-field
- [ ] https://github.com/digdir/designsystemet/issues/2511
- [ ] https://github.com/digdir/designsystemet/issues/1711
- [ ] https://github.com/digdir/designsystemet/issues/2347
- [x] Added animation to the `spinner`component
- [x] `spacing-2` gap on pagination
- [x] fixed broken variables on check/radio buttons
- [ ] https://github.com/digdir/designsystemet/issues/2617
- [x] Combobox: Height should adjust to content
- [x] Radio: Reset validationMessage in Radio so that it uses the errormessage-icon
- [x] ValidationMessage set to AutoHeight and Fill width
- [x] Switch: Large Switch with label left had medium text size, changed this to large.
- [x] Card - Set subtitle top and bottom + slot to "fill width"
- [x] Slot: Change Slot border to "inside" instead of "outside"
- [x] TextArea Added min-height
- [x] TextField: Set the layer .base-container to fill-width
- [ ] https://github.com/digdir/designsystemet/issues/2804
- [x] Variables: Mode -> Colorscheme
- [x] Variables: New color modes main and support
- [x] Variables: New Border-radius tokens
- [ ] https://github.com/digdir/designsystemet/issues/1102
- [ ] https://github.com/digdir/designsystemet/issues/1092
- [x] Button: Added loading states for both default and disabled states
```

**Comment by Febakke** [comment]
#2183 is solved and published to community in a quick fix.

**Comment by mrosvik** [comment]
Published to community 23. nov 2024.
