### ISSUE TITLE
New component: DropdownMenu

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#219]
### Related issues or relevant information?

- https://aksel.nav.no/komponenter/interne/dropdown
- https://atlassian.design/components/dropdown-menu/examples

Related components: 
- [Header](https://github.com/digdir/designsystem/issues/216)

![image](https://user-images.githubusercontent.com/1464915/223989171-205d0941-8d60-47ef-b839-2e0975cbe773.png)

![image](https://user-images.githubusercontent.com/1464915/223991902-8cf150ce-e75f-426b-9646-955101cfb72e.png)

```[tasklist]
### Tasks
- [ ] DropdownMenu: Specification
- [ ] https://github.com/digdir/designsystemet/issues/1482
- [ ] https://github.com/digdir/designsystem/issues/1067
- [ ] DropdownMenu: WCAG-Test
- [ ] https://github.com/digdir/designsystem/issues/1073
```

**Comment by indiamaydesign** [comment]
- https://github.com/digdir/insights-hub/issues/26

This finding might be relevant for this component 😊

**Comment by mrosvik** [comment]
Thank you so much for sharing and linking, @indiamaydesign! 🙌

**Comment by mrosvik** [comment]
Suggestion from Team Arbeidsflate: DropDownMenu should be more flexible. @ingefossland will describe the needs.

**Comment by ingefossland** [comment]
> Suggestion from Team Arbeidsflate: DropDownMenu should be more flexible. @ingefossland will describe the needs.

Still work-in-progress, but we are considering a pattern for filtering using dropdowns on desktop, with drawers on mobile. Elements inside can multiple things depending on the filter. (See attached sketches.)

To accommodate for different content and make dropdowns more flexible I would suggest:

1. Separating the dropdown container from the menu (menu groups and items might make sense elsewhere as well).
2. Consider removing initial padding on the dropdown container.
3. Create a pattern for drawers.

![Select multiple](https://github.com/digdir/designsystemet/assets/1138656/99adfee2-4b2c-4dec-994a-b83485daa345)
![Select date+time](https://github.com/digdir/designsystemet/assets/1138656/d2d57ac3-d102-4fbb-8316-3ae4234f5f6c)
![Drawers](https://github.com/digdir/designsystemet/assets/1138656/ae64478e-9168-4204-b5fd-b9af1abb9e7c)

**Comment by mrosvik** [comment]
The `DropdownMenu` is ready for use: https://storybook.designsystemet.no/?path=/docs/felles-dropdownmenu--docs
