### ISSUE TITLE
React component tweaks after testing with Mattilsynet

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2280]
Tweaks, fixes and improvements after Mattilsynet has tested React components for common use-cases.
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/2281
- [ ] https://github.com/digdir/designsystemet/issues/2279
- [ ] https://github.com/digdir/designsystemet/issues/2278
- [ ] https://github.com/digdir/designsystemet/issues/2282
- [ ] https://github.com/digdir/designsystemet/issues/2283
```

**Comment by mrosvik** [comment]
We should use epic to group issues based on subject/category, not who they are reported by.
