### ISSUE TITLE
Chip: Improve styling and behavior

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2321]
We need to revise the `chip` component. 

- Should it have more visible checkbox/radios? 
- Should fit better with the rest of the component-API

**Comment by mrosvik** [comment]
New design suggestion: 

![Image](https://github.com/user-attachments/assets/2690a923-de59-4eb5-abcb-dba4720fab98)

This should make it clearer which chips that could be selected as single (radio) and witch could be selected multiple (checkbox) 

----

**Summary of our discussions:** 

Initially, we considered simplifying the Chip component to only be "Removable" and keeping it as an internal component for use in the Combobox. However, we've noticed some developers have already used it in other contexts, so we need to evaluate that.

We considered to remove the Chip Checkbox, and update `Checkbox` with a new variant with a chip design. This chip variant of the checkbox will be used when placed horizontally. Similarly, the Chip Radio was considered to be removed, and Radio updated with a new variant with a chip design to be used when placed horizontally. For ToggleGroup, we were also considering a chip design variant.

After further discussion with developers, we considered keeping the `Chip` as a standalone component with all variants, as it would be easier to locate in the documentation.  If we find a better way in the future, we can always deprecate some of it.

**Comment by mrosvik** [comment]
New design is finished in Figma. 

```[tasklist]
### Tasks
- [ ] Add all states
- [ ] Add relevant examples
- [ ] Old Chip is moved to workspace
- [ ] Combobox is updated with new chip
```


![Image](https://github.com/user-attachments/assets/cc031a99-cb68-408f-83b6-5e88b08f0c29)
