### ISSUE TITLE
More flexible color theming

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2370]
## Møte "Fargefloka" 4. september 2024
Udir har delt sin erfaring med bruk av temabyggeren og tokens-oppsettet.

### Hovedproblem 
Slik tokens er satt opp nå med èn `accent`-farge, er ikke systemet fleksibelt nok. Udir og Mattilsynet har grønn som primærfarge. De ønsker denne grønnfargen på noen av de interaktive komponentene, men den passer seg ikke til alle. Når den samme fargen brukes på alle interaktive element blir det en for høy vekting av denne fargen (den blir mer fremtredende enn ønskelig). 

Det er ikke gitt at radioknapper og vanlig knapper MÅ ha samme farge. Dette vil være ulikt fa organisasjon til organisasjon. Vi må lage det fleksibelt nok til at en virksomhet selv kan bestemme om `Button` skal ha samme farge som `radio` f.eks.

### Forslag om å utvide accent
- Det ble foreslått å utvide accent til flere skalaer. 
- Eksempel fra token-struktur hos Møller: https://gnist.moller.no/latest/?path=/docs/foundation-colors-overview--docs 

### Komponent-tokens eller ikke?
- Fordel: De gir mulighet til å sette en komponent til accent og en annen til neutral f.eks. Det gir deg veldig mye fleksibilitet.
- Ulempe: Det blir veldig komplekst både å lage og holde oppdatert hvis noen endrer disse verdiene. 

### Oppfølgingspunkt

- [x] Teste om vi kan utvide fargeskalaen med flere farger. Utvide accent til flere skalaer. 
- [x] Hvordan løser vi dette i praksis? I Figma og i kode? Enten gjennom varianter i Figma, eller gjennom tokens-logikk. 
- [x] Arbeidsmøte med teamet for å se på mulige løsninger
- [x] Presentere forslag til Udir

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/2373
- [ ] https://github.com/digdir/designsystemet/issues/2507
- [ ] https://github.com/digdir/designsystemet/issues/2655
```

**Comment by Febakke** [comment]
En liten utfordring til! 
Mitt inntrykk er at det veldig ulikt hvordan fargesystem er laget for profilene til ulike aktører, det gjelder også hvor mange farger de forskjellige aktørene har. 

Om vi nå setter det opp med primær, sekundær og accent. Vil en virksomhet kunne si at de kun trenger primær og accent? Hvordan vil det påvirke token strukturen. Eller skal vi be dem om å legge til flere farger i så fall?

**Comment by mimarz** [comment]
Første jeg tenker er en kombinasjon av alternativ 2 (som @Febakke foreslår) og neutral color på form components (og/eller generelt alle som har accent farge). 

En begrensning blir antall sets du kan ha i Figma (4stk) utenom enterprise prising, og at de kan fritt endres i Figma? 

Vi kan så utvide koden til at du bestemmer hvilket tema/brand/kontekst som brukes på en kontekst. Da vil de i kode hvertfall kunne definere det i sine "wrapper" komponent for designsystemet.

Pseudo-kode:
```tsx
// Primær accent grønn farge
<UdirButton>
  <Button data-ds-theme="udir" />
<UdirButton>

// Tonet ned grønnfarge?
<UdirFormButton>
  <Button data-ds-theme="udir-subtle" />
<UdirFormButton>

// Eller bare bruke atributtet uten wrapper komponent
// Alle inneværende komponenter vil bli endre tema
<div data-ds-theme="udir-subtle">
 <form>
   <Textfield />
   <Fieldset />
   <Checkbox />
   <Radio />
   <Button data-ds-theme="udir"> // <- Dersom du må ha unntak fra inneværende kontekst
</Fieldset>

 </form>
</div>
```

**Comment by Febakke** [comment]
Tenker du at dette løses noe som dette i Token strukturen?

1. Primary, secondary og accent må ligge som hex koder i primitives. For å støtte dark/light/kontrast modes
2. De blir sendt videre til brand collection slik at man kan endre mellom for eksempel Digdir og Altinn
3. Mellom brand og det semantiske laget må vi legge til et set til som tar i mot primary, secondary og accent.
Her vil man kontekst styre hvilken farge som vil bli sendt til det semantiske laget.

NB: En konsekvens av dette vil være at du ikke kan bruke primary og secondary i samme kontekst.

![Skjermbilde 2024-09-05 kl  09 07 49](https://github.com/user-attachments/assets/5ee88b5e-83ee-4978-b03a-69c1e778f749)

**Comment by mimarz** [comment]
> Tenker du at dette løses noe som dette i Token strukturen?
> 

Nei, tenker vi kunne løst det uten å røre tokens-strukturen. Det blir bare litt justeringer på det rundtliggende.

**Comment by Febakke** [comment]
Om vi ikke endrer token strukturen må vi gå for løsning 1 eller 3 som jeg nevnte over her. Jeg er ganske sikker på at 1 blir uaktuelt da det vil gjøre komponentbiblioteket gigantisk. 3 tror jeg er mer realistisk og vil fungere bra så lenge de som tar det i bruk ikke skal endre mellom accent og primary på button. (En work-around er jo at de lager varianter internt der de trenger det)

**Comment by mimarz** [comment]
This has been solved with the `data-color` feature #2507
