### ISSUE TITLE
Remove `spacing` as property from our Typography components

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2491]
_This is a summary of meeting held on Typography components and our `spacing` property._

We will remove the `spacing` property as its up to the individual organisations to decide how spacing between their typography elements. 

We will create an article on recommended typography use with spacing between the individual types.

A helper component to achieve the same result was proposed for a later date #2492 

See discussion in https://github.com/digdir/designsystemet/issues/2295#issuecomment-2298686674 regarding margin
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/2490
- [ ] https://github.com/digdir/designsystemet/issues/2524
- [x] Update components using `spacing` to alternative
- [x] update components using spacing
- [x] update apps where we use spacing
```

**Comment by mrosvik** [comment]
All issues done
