### ISSUE TITLE
Paragraph changes for v1

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2503]
We agreed on daily today to simplify `Paragraph` and paragraph typography style.

- Rename typography style paragraph to body
- Remove ingress/lead - use body long instead
- Remove `short` variant from `Paragraph`
  - Review if we still need body/paragraph short internally in the end.

```[tasklist]
### Tasks
- [x] Rename typography style paragraph to body
- [x] Remove `Ingress` component in react
- [ ] https://github.com/digdir/designsystemet/issues/2528
```

**Comment by Barsnes** [comment]
closing as completed
