### ISSUE TITLE
Darkmode on/off switch in storefront

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2660]
We should add a DarkMode-toggle in the storefront to demonstrate that we use our own functionality. This reinforces our flexibility for different user preferences, and aligns with modern accessibility and usability expectations. It will also make it easier for us to test that dark mode works in various cases.

```[tasklist]
### Tasks
- [ ] Create a simple dark mode switch.
- [ ] Ensure the design works well in both light and dark modes.
- [ ] Adapt all illustrations, icons, and visual elements to ensure they display correctly in dark mode without losing clarity or accessibility.
```

**Comment by Barsnes** [comment]
This is blocked by the reason we removed it: #29189
We would either have to wait, or downgrade storybook.

**Comment by mrosvik** [comment]
@Barsnes I meant storefront, not storybook :)

**Comment by Barsnes** [comment]
We do already use dark mode on the storefront, just not for the whole page.
We use it in the footer, and some codeblocks

**Comment by mrosvik** [comment]
A switch between dark and light mode for the whole page should still exist. :)
