### ISSUE TITLE
Sizing adjustments

### ISSUE THREAD

**Issue by eirikbacker** [digdir/designsystemet#2665]
```[tasklist]
### Tasks
- [x] Scale icons also in Badge and other places (search for `fontSize=`) based on font
- [x] Scale underline on links
- [x] Scale border on active tab
- [x] Scale inset to checkmark in `input[type="checkbox"]` and circle in `input[type="radio"]`
- [x] Adjust Avatar (maybe use `initials` instead of `children`) and land wether it is typographically a heading
- [x] Double check spacing in fieldset/between radio/checkboxes
- [x] Figma: gap 2 on Pagination
- [x] Spacing icon in link
- [x] Gap in Tags story?
- [x] Remove unused sizes for Label and ValidationMessage
```
