### ISSUE TITLE
Create Themebuilder design for v1

### ISSUE THREAD

**Issue by Thunear** [digdir/designsystemet#2684]
New design and functionality for the themebuilder to support all the new features we want to add to theming.

Figma prototype [here](https://www.figma.com/proto/judccEgnoUOytf1fNSCbbz/Temabygger?page-id=1%3A55&node-id=48-140&node-type=frame&viewport=11664%2C-5892%2C1.22&t=goqaDa0wWG9bXbCq-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=48%3A140).
FIgma file [here](https://www.figma.com/design/judccEgnoUOytf1fNSCbbz/Temabygger?node-id=1-55&t=tYZIQGqoak7Rwhrf-1).
```[tasklist]
### Tasks
- [x] Create and prototype system for managing colors in the themebuilder, then test it on users in the team.
- [ ] Add dark mode support to the themebuilder
- [ ] Add border radius system
- [ ] Add back "share theme" functionality
- [ ] Create 2 themes for the preview sections on the front page
- [ ] https://github.com/digdir/designsystemet/issues/2686
```
