### ISSUE TITLE
Add themebuilder link in header

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2686]
```[tasklist]
### Tasks
- [x] Add link to themebuilder in header
- [x] Update Themebuilder header with the same menu as designsystemet.no. Make sure "Themebuilder" is active.
- [x] Move information on https://next.theme.designsystemet.no/slik-bruker-du-verktoyet to designsystemet.no/Grunnleggende
```

**Comment by mrosvik** [comment]
This is done
