### ISSUE TITLE
Should `ValidationMessage` change icon based on the color?

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2722]
```[tasklist]
### Tasks
- [x] Investigate if ValidationMessage should change icon based on the color
- [x] Update ValidationMessage in Figma
- [x] Update ValidationMessage in code
- [ ] Update article about validationMessage to use correct icons.
```

**Comment by Viveca24** [comment]
**Fordeler:** Det visuelle designet forsterker budskapet, gjør informasjon raskere å tolke, og ser bedre ut visuelt.

**Ulemper:** Det kan være en risiko for forvirring ved inkonsekvent bruk. Erfaringene fra systemvarsel-artikkelen viser at vi må være tydelige på når de ulike fargene og ikonene skal brukes, dette er ofte situasjonsbasert.

Jeg er usikker på om dette vil øke kompleksiteten i utvikling og vedlikehold.

**Comment by mrosvik** [comment]
Hva bør vi anbefale i dette scenariet? `ValidationMessage` eller `Alert`? En kombinasjon? 

![Image](https://github.com/user-attachments/assets/943339db-9209-45a7-85c1-59c198d64cad)

**Comment by mrosvik** [comment]
Vi har konkludert med at Alternativ 1 er best, og at vi derfor bør tilby validationmessage i alle severity-farger med tilhørende ikon.

**Comment by mrosvik** [comment]
ValidationMessage in Figma is updated with 5 variants: 

![Image](https://github.com/user-attachments/assets/726fba74-9583-4f92-adf7-49de41a5f66c)


![Image](https://github.com/user-attachments/assets/e3957e88-77b6-44cb-9c6c-e28b59ea7483)


![Image](https://github.com/user-attachments/assets/3c79fbc1-a14b-4742-bc26-929d68150cbd)

**Comment by mrosvik** [comment]
Reopened since we also have to update article about validationMessage to use correct icons.

**Comment by mrosvik** [comment]
We should look more into the icons. It looks weird when plasced under checkboxes and radios. Also: Its weird to have a neutral variant on a validatiion message. Neutral is not validation.

**Comment by mrosvik** [comment]
The new design causes a problem for checkboxes and radio: 

![Image](https://github.com/user-attachments/assets/042bc36a-9c77-40e5-acb4-b3f99d7f2e9d)
