### ISSUE TITLE
Figma community V1 Release candidate - 4

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2825]
### Tasks
- [x] New sizing tokens
- [ ] https://github.com/digdir/designsystemet/issues/2506
- [x] New `Radio` component
- [x] New `Checkbox` component
- [x] New `Textfield` component
- [x] New `Textarea` component
- [ ] https://github.com/digdir/designsystemet/issues/2781
- [ ] https://github.com/digdir/designsystemet/issues/2843
- [ ] https://github.com/digdir/designsystemet/issues/2822
- [x] Renamed ErrorMessage to ValidationMessage
- [x] Renamed Modal to Dialog
- [x] Added success, warning, info severitys to ValidationMessage
- [ ] https://github.com/digdir/designsystemet/issues/2722#issue-2628643618
- [x] Create main, support and neutral components
- [x] Added Badge as an option in Tabs
- [ ] https://github.com/digdir/designsystemet/issues/3120
- [ ] https://github.com/digdir/designsystemet/issues/3157
- [ ] https://github.com/digdir/designsystemet/issues/3050
- [ ] https://github.com/digdir/designsystemet/issues/3065
- [ ] https://github.com/digdir/designsystemet/issues/2937
- [ ] https://github.com/digdir/designsystemet/issues/3135
- [x] New `Suggestion` and `Multiselect` component (Replaces the old `combobox` component)
- [x] Suggestion and multiselect list should not have description turned on by default
