### ISSUE TITLE
Explore Workflow: Using AI to Help Write Documentation

### ISSUE THREAD

**Issue by simon-archer** [digdir/designsystemet#2850]
Exploring the possibilities of a workflow that uses AI to help create and improve documentation for the design system, specifically for use in Storybook as developer documentation. The goal is to make the process faster and easier while ensuring the documentation meets the needs of different users, follows guidelines, and highlights alternative standards used by others, such as NAV and Skatteetaten.

**Scope:**
- Trying out AI tools to create draft documentation.
- Setting up a simple way to review and improve the drafts.
- Finding a way to show which parts of the guidelines are flexible or strict.

**Tasks:**

- [x] Test AI tools (e.g., ChatGPT and Claude) to create sample documentation (Tested for; Tags, Tabs and Accordion)
- [ ] Sketch a simple review process to improve AI-generated drafts.
- [ ] Explore ways of indicating parts of the documentation as flexible or strict.
- [ ] Review, feedback and discussion with rest of team.

**Comment by simon-archer** [comment]
**Erfaringer fra prosessen med AI-assistert dokumentasjon**

**1. Hva som funket**
AI-verktøyene (ChatGPT, Claude) var gode til å skrive dokumentasjon, men slet med å lage kode og Stories i Storybook. Etter forsøk med å bruke AI til å skrive kode for Stories og bruke designsystemet ser jeg at det er beder å fokusere på tekst-baserte delen av dokumentasjonen nå.

**2. Utfordringer i arbeidsflyten**
Dokumentasjon ligger spredt på ulike plattformer (tekst i Word, og Markdown/kode i Storybook). Dette gjør arbeidsflyten litt treg og komplisert. Jeg ser behov for et system som kan få guidelines fra start til prod på en mer strømlinjeformet måte - så både mennesker og ai kan lett forstå hvor man starter og hvilke faktorer som er viktige på veien.

**3. Bruk av AI fremover**
AI kan kanskje lage førsteutkast til flere komponenter og hjelpe med å finne uoverensstemmelser mellom dokumentasjon og kode.

**4. Veien videre**
Det er nødvendig å utvikle en enklere og mer effektiv arbeidsflyt for å skrive og oppdatere dokumentasjon. Dette inkluderer å definere klare faktorer og kilder som kan brukes for å validere kvaliteten på dokumentasjonen.

Markerer denne som closed for nå, siden jeg har laget en ny issue for å ta tak i dette: [Link til ny issue]
