### ISSUE TITLE
Merge `sizing` and `spacing` tokens into `size`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2927]
We currently have two identical sets of tokens used for spacing and sizing. This was due to limitations in Figma and Token Studio. With support for Figma variables and W3C DTCG format in Token Studio, we no longer need to have to distinct sets of variables.

We should reduce this to just one set, so there is less variables and easier to use for end-users. This is also to reduce unneeded maintenance in general for duplicate sets.

Current suggestion is to keep it as simple and short as possible:
## `sizing` and `spacing` -> `size`

```css
padding: var(--ds-size-2);
height: var(--ds-size-6);
gap: var(--ds-size-4);
```
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystemet/issues/2934
- [x] Rename sizing Figma variables
- [ ] https://github.com/digdir/designsystemet/issues/2938
- [ ] https://github.com/digdir/designsystemet/issues/2937
```
