### ISSUE TITLE
New component: ToggleGroup

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#304]
## Related information and insight
- https://uxdesign.cc/the-good-the-bad-and-the-toggle-2abc0fbbd099
- https://aksel.nav.no/komponenter/core/toggle-group#togglegroupdemo-label
- https://www.radix-ui.com/primitives/docs/components/toggle-group
- https://components.ruter.as/#/Components/Forms/RadioButtonGroup
- https://primer.style/design/components/segmented-control
- https://design-system.w3.org/styles/forms.html#segmented-options
- https://mantine.dev/core/button/#buttongroup
- https://www.w3.org/WAI/ARIA/apg/patterns/tabs/

## Specification and requirements
- Only one option can be chosen at a time from a predefined set of options.
- The buttons should have the same width, based on the longest input:

![Image](https://github.com/digdir/designsystem/assets/1464915/fa662daf-c3d6-4541-9512-bcb8f96f3162)

- Size: Small, medium, large (same as button size)
- Label and description
- Support for only text, only icon, both icon and text (icon should be placed left to text)
- Controlled? Should have a default value
- Use buttons with roles for radio 

Additional options later: 
- Add vertical support (direction/orientation?)
- With tooltip (maybe not a prop, but users can add it)

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/801
- [ ] https://github.com/digdir/designsystem/issues/804
- [ ] https://github.com/digdir/designsystem/issues/806
- [ ] https://github.com/digdir/designsystem/issues/805
- [ ] ToggleGroup: WCAG-Test
```

**Comment by mrosvik** [comment]
The `ToggleGroup` component is ready for use: https://storybook.designsystemet.no/?path=/docs/felles-togglegroup--docs
