### ISSUE TITLE
Improvements for: Button

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#315]
```[tasklist]
### Improvements
- [ ] https://github.com/digdir/designsystem/issues/204
- [ ] https://github.com/digdir/designsystem/issues/224
- [x] https://github.com/digdir/designsystem/issues/229
- [ ] https://github.com/digdir/designsystem/issues/551
- [ ] https://github.com/digdir/designsystem/issues/553
- [ ] https://github.com/digdir/designsystem/issues/537
- [ ] https://github.com/digdir/designsystem/issues/440
- [ ] https://github.com/digdir/designsystem/issues/595
- [ ] https://github.com/digdir/designsystem/issues/657
- [ ] https://github.com/digdir/designsystem/issues/821
- [ ] https://github.com/digdir/designsystem/issues/825
- [ ] https://github.com/digdir/designsystem/issues/820
- [ ] https://github.com/digdir/designsystem/issues/881
- [ ] https://github.com/digdir/designsystemet/issues/1449
- [ ] https://github.com/digdir/designsystemet/issues/1542
```

[Link to Figma design](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?node-id=6631%3A19868&t=7Q2N4sUdQGhFZrPh-1)
