### ISSUE TITLE
Improvements for: Checkbox

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#316]
### Related issues

```[tasklist]
### Tasks
- [x] https://github.com/digdir/designsystem/issues/163
- [ ] https://github.com/digdir/designsystem/issues/250
- [ ] https://github.com/digdir/designsystem/issues/629
- [ ] https://github.com/digdir/designsystem/issues/65
- [ ] https://github.com/digdir/designsystem/issues/630
```

**Comment by Barsnes** [comment]
All linked issues are closed, should we close this epic?
