### ISSUE TITLE
Improvements: (Legacy) Select

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#320]
It is decided to divide the existing `Select`component into multiple components: 

- `Autocomplete` (single og multi)
- Select (group in Storybook):
  - `Select` (should support formating in dropdown) Could be based on Floating UI?
  - [`NativeSelect`](https://github.com/digdir/designsystem/issues/482)

This existing `Select` component will be renamed to `Legacy Select`

### Related issues to Legacy select:

```[tasklist]
### List of identified improvements for our existing Select component:
- [ ] https://github.com/digdir/designsystem/issues/55
- [ ] https://github.com/digdir/designsystem/issues/66
- [ ] https://github.com/Altinn/app-frontend-react/issues/116
- [ ] https://github.com/digdir/designsystem/issues/180
- [ ] https://github.com/Altinn/altinn-design-system/issues/201
- [ ] https://github.com/digdir/designsystem/issues/270
- [ ] https://github.com/digdir/designsystem/issues/274
- [ ] https://github.com/digdir/designsystem/issues/298
- [ ] https://github.com/digdir/designsystem/issues/314
- [ ] https://github.com/digdir/designsystem/issues/307
- [ ] https://github.com/digdir/designsystem/issues/368
- [ ] https://github.com/digdir/designsystem/issues/398
- [ ] https://github.com/digdir/designsystem/issues/600
- [ ] https://github.com/digdir/designsystem/issues/607
- [ ] Select: Fix testing errors/warnings
- [ ] Select: Wrong option is read out when de-selecting by MacOs VoiceOver on Chromium
- [ ] Support for deleting selected options on `Backspace` in Select
- [ ] Support for floating dropdown on Select
- [ ] https://github.com/digdir/designsystem/issues/464
```

**Comment by mrosvik** [comment]
Vi har hatt et arbeidsmøte rundt Select-komponenten (i forbindelse med flere bugs som har blitt rapportert) og innser at denne komponenten skal løse veldig mye og dermed blir kompleks. Andre designsystem løser dette ofte med flere komponenter. Inntil videre skal vi supportere den eksisterende select-komponenten som er i bruk og fikse de mest kritiske bugsene på denne. Litt mer langsiktig tenker vi det kan være lurt å dele opp komponenten i mer avgrensede oppgaver:
- En [Autocomplete-komponent](https://eds.equinor.com/0b0c666ab/p/31ae8d-autocomplete/b/86826a) som støtter - enkeltvalg og flervalg
- En select-komponent som støtter formatering i dropdown
- En NativeSelect

Eksisterende Select-component blir fra nå av kalt `Legacy Select`.

**Comment by mimarz** [comment]
This is no longer relevant
