### ISSUE TITLE
Release managment

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#425]
Notes:
- https://apolloelements.dev/blog/lerna-to-changesets/

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/172
- [ ] https://github.com/digdir/designsystem/issues/167
- [ ] https://github.com/digdir/designsystem/issues/175
- [ ] https://github.com/digdir/designsystem/issues/459
- [x] Separate dev / production storybook
- [ ] https://github.com/digdir/designsystem/issues/842
- [ ] https://github.com/digdir/designsystemet/issues/1885
```
