### ISSUE TITLE
🧭 Roadmap 2023

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#468]
## Fokus Q1 2023
**Etablere team og forstå behov:**
- Forstå eksisterende design i ulike produkter
- Identifisere behov som går igjen på tvers
- Hvilke designelementer, komponenter og mønstre gir det mening at gjenbrukes på tvers
- Hvem bør involveres fra starten

**Utforske grunnleggende oppsett for designsystemet**:
- **Grunnleggende designelementer**
Håndtering og struktur av styles, farger, typografi, grid, avstander, ikoner, osv.<br/>
-  **Grunnleggende komponenter**
Design og utvikling av komponenter i Figma og Storybook.<br/>

I løpet av januar skal vi ha:
- [x] Etablert et designsystem-Team (Sprint-aktiviteter, roadmap, backlog, prioritert oversikt over planlagte komponenter)
- [x] Gjennomført gameplan-Workshop
- [x] Publisert en første versjon av Designsystemet (Storybook)
- [x] Fått minst 3 produktteam til å delta i ukentlig designsystem-sync

I løpet av februar skal vi ha:
- [x] Ferdigstillt gameplan og startet på forankring av målbildet i org
- [x] Flyttet over relevante komponenter fra Altinn-storybook til ny felles Storybook
- [x] Oppgradert til Figma Organizations + Ryddet opp i Figma Assets
- [x] Tech Lead på plass

I løpet av mars skal vi ha:
- [x] Designet og utviklet en betaversjon av minst 8 av de mest etterspurte komponentene
- [x] Utforsket og testet grunnleggende designelementer

Q1 Milestone: https://github.com/digdir/designsystem/milestone/1 

--------

## Fokus Q2 2023
**Lande konsept, grunnleggende designelementer og oppsett**

I løpet av april, mai og juni skal vi ha:
- [x] Tatt i bruk fluid design i tokens
- [x] Planlagt hvilke komponenter som skal inn i felles designsystem V1 og hvilke behov de skal dekke. [Se oversikten her](https://digdir.github.io/designsystem/?path=/docs/komponentoversikt--docs).
- [x] Oppdatert til Storybook 7
- [x] Fått med minst 3 team på utvikling av komponenter
- [x] Laget et hjem for felles dokumentasjon, retningslinjer, god praksis og eksempler på bruk av komponenter
- [x] Lansert en beta-versjon av Designsystemets dokumentasjon (Nextjs) på designsystemet.no

Q2 Milestone: https://github.com/digdir/designsystem/milestone/2 

----

## Fokus Q3 2023
Få eksisterende komponenter (fra andre bibliotek) opp på ønsket nivå.

August og september:
- [x] Gjennomgå eksiterende komponenter slik at de er bygget opp på samme måte og følger samme oppsett
    - [x] React
    - [x] Figma
- [x] Publisere komponentbiblioteket i Figma Community
- [x] Markedsstrategi, WS med Marked/Kom
- [x] Promotere designsystemet og få med flere på samarbeidet
- [x] Dokumentasjon for hvordan bygge opp komponenter på riktig måte

Q3 Milestone: https://github.com/digdir/designsystem/milestone/3

----

## Fokus Q4 2023
- Få eksisterende komponenter (fra andre bibliotek) opp på ønsket nivå.
- Nye komponenter (V1)

I løpet av oktober, november og desember skal vi ha:
- [x] Laget minimum 5 nye komponenter som skal være del av V1.
- [x] Invitert til åpen workshop rundt felles designsystem
- [x] Fått med minst en annen aktør i utviklingen av felles designsystem
- [ ] Gjennomført undersøkelse om bruk og user satisfaction 

Q4 Milestone: https://github.com/digdir/designsystem/milestone/4

----

**Comment by mrosvik** [comment]
Roadmap for 2024 will be published in: https://github.com/digdir/designsystemet/issues/1435
