### ISSUE TITLE
Radio: Write guidelines for usage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#523]
```[tasklist]
### Tasks
- [x] Finne stoff og kvalitetssikre
- [x] Skrive utkast
- [x] Sende til Dorte for kvalitetssikring
- [x] Justere etter tilbakemelding
- [x] Dele med Marianne
- [ ] Marianne gir meg beskjed om eventuelle endringer og setter til Done
```

**Comment by Camulos** [comment]
Radiogruppe: burde inkludere retningslinjer som sier noe om når en radiogruppe er hensiktsmessig og hvilke andre komponenter en burde vurdere dersom en har tilfeller hvor radioknapp/gruppe ikke helt gir mening. 
En slik seksjon kan være nyttig å legge til på alle komponenter?

Forslag til noen retningslinjer, hjelp til å velge rett og bruke på riktig måte:

- radiogruppe er hensiktsmessig når en skal la brukeren velge mellom 2 til 5 alternativer og maks ett av alternativene kan være valgt samtidig
- er det flere enn 5 valg kan en select komponent (for eksempel native select) være et bedre valg
- er det for å skru av eller på en funksjon eller et valg, for eksempel med ja og nei radioknapper, kan det hende at en toggle, toggle-gruppe eller sjekkboks er mer hensiktsmessig
- vis radioknappene innenfor en radiogruppe på hver sin linje, med mindre det er 2-3 valg med kun korte labels og det er behov for å komprimere

**Comment by Ildest** [comment]
Startet på denne i dag

**Comment by Ildest** [comment]
Dokumentert og sendt til Dorte for gjennomgang

**Comment by Ildest** [comment]
Levert til @mrosvik  7.11

**Comment by Ildest** [comment]
Status  by 21. March: Draft submitted in https://digdir.sharepoint.com/:w:/r/sites/bod-bbo/Delte%20dokumenter/Team%20Designsystem/God%20praksis%20og%20retningslinjer/Komponenter/Radio.docx?d=w163a879da48940be8da088da2d53c1d9&csf=1&web=1&e=ouacOb

**Comment by Ildest** [comment]
@mrosvik kommentaren over om radiogruppe bør vel stå på issue om radio group? Den er ikke dokumentert enda.
