### ISSUE TITLE
New component: Combobox

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#525]
## Combobox
The `ComboBox` component combines a dropdown list with an editable text input, allowing users to select an option from a predefined list or enter a custom value.

### Related information and research findings:
- [Autocomplete in Equinor design system](https://storybook.eds.equinor.com/?path=/docs/inputs-autocomplete--docs)
- [Combobox in Aksel](https://aksel.nav.no/komponenter/core/combobox)

### Autocomplete requirements/specification

- Should come in three sizes `small`, `medium`, `large`
- Default Value: empty
- Clicking on the field should toggle the visibility of the predefined list.
- Users can select an option from the dropdown list or type a custom value in the input field. 
- When the user starts typing the list should filter options, but keep the order.

Variants
- Single: If only one option can be selected, there should _not_ be checkboxes.
- Multi: If multiple options can be selected, there should be checkboxes to the left in the options.
- With autocomplete: With autocomplete, a choice from the list is suggested that matches what the user writes.
- Option to show selected options as `chips` inside the field, Should also be possible to display them where you want outside. 

#### Accessibility
- Ensure the ComboBox is fully navigable using the keyboard, including arrow keys and Enter for selection.
- Correct use of ARIA attributes

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/772
- [x] Write specification / functional requirements
- [ ] https://github.com/digdir/designsystem/issues/1091
- [ ] https://github.com/digdir/designsystem/issues/64
- [ ] https://github.com/digdir/designsystem/issues/1090
- [x] Combobox: WCAG Test
- [ ] https://github.com/digdir/designsystemet/issues/1340
```

**Comment by mrosvik** [comment]
The `Combobox` component is ready for use: https://storybook.designsystemet.no/?path=/docs/felles-combobox--docs
