### ISSUE TITLE
Pagination: Write guidelines for usage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#540]
```[tasklist]
### Tasks
- [x] Finne bakgrunnsstoff fra gov.uk og nav og kvalitetssikre
- [ ] Skrive utkast
- [ ] Sende utkast til Dorte eller Gørild for gjennomgang
- [ ] Innarbeide eventuelle endringer
- [ ] Sende til Marianne
- [ ] Gå gjennom når M har lagt den i Storybook
- [ ] Marianne lukker saken
```

**Comment by Ildest** [comment]
Kilder:

https://aksel.nav.no/komponenter/core/pagination

https://designsystem.dk/komponenter/paginering/

https://carbondesignsystem.com/components/pagination/usage/

https://design-system.service.gov.uk/components/pagination/

**Comment by Ildest** [comment]
Status by 21. March: Draft submitted in https://digdir.sharepoint.com/:w:/r/sites/bod-bbo/Delte%20dokumenter/Team%20Designsystem/God%20praksis%20og%20retningslinjer/Komponenter/Pagination.docx?d=w94818c9e59dd41e38306feddb6491e28&csf=1&web=1&e=9fFLod
