### ISSUE TITLE
Switch: Write guidelines for usage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#645]
```[tasklist]
### Tasks
- [x] Se på eksisterende info for dette
- [x] Samle informasjon om komponenten
- [x] Skrive utkast
- [x] Sende utkast til gjennomsyn hos Dorte
- [x] Innarbeide kommentarer fra Dorte
- [ ] Legge opp i Figma
- [x] Informere Marianne/sette til review
- [ ] Marianne gir beskjed om jeg skal se over endringer i Storybook og setter til Done
```

**Comment by mimarz** [comment]
Fikk tilbakemelding at det var ikke helt tydelig hvordan hvordan `Switch` skulle brukes i kode ved å bare se på dokumentasjonen. Når jeg nevnte at det var bare en `<input type="checkbox" />` så var det tydeligere hva som var forventet mtp. props og bruke.

**Comment by Ildest** [comment]
Dokumentasjonen er nylig oppdatert/nyskrevet. Den ligger hosMarianne for gjennomgang nå, så håper det blir bedre :-).

**Comment by Ildest** [comment]
Dokumentasjonen er  sendt Marianne i dag

**Comment by Ildest** [comment]
Ready for update in Storybook after @Febakke and I reviewed it today.
