### ISSUE TITLE
New component: Accordion

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#75]
## Related information and insight
- Gov UK: https://design-system.service.gov.uk/components/accordion/
-  Aksel: https://aksel.nav.no/komponenter/core/accordion
- Carbon: https://carbondesignsystem.com/components/accordion/usage/
- Entur: https://design.entur.no/komponenter/layout-og-flater/expandable
- EDS: https://storybook.eds.equinor.com/?path=/docs/surfaces-accordion--docs

## Accordion
Accordion allows users to display and interact with collapsible sections of content. It is commonly used to present information in a compact and organized manner, allowing users to expand and collapse sections as needed. An accordion can work well if the user needs to reveal and compare information that’s relevant to them.

An accordion could help the user to:
1) See an overview of multiple, related sections of content
2) Choose to show and hide sections that are relevant to them
3) Look across information that might otherwise be on different pages

### Specification
- Should support both single-open mode (only one section can be expanded at a time) and multi-open mode (multiple sections can be expanded simultaneously).
- The expansion and collapse of sections should be accompanied by smooth and visually appealing animations. https://altinndevops.slack.com/archives/C03L53RFPRU/p1681386295901419
- Keyboard Navigation: Users should be able to navigate through the accordion sections using the keyboard, such as using the arrow keys to move between sections and the spacebar or enter key to expand or collapse sections.
- Should support different types of content, such as text, images, or other components.
- Expand/Collapse Icons: The headers of the accordion sections should include expand and collapse icons to provide visual feedback to users. The icons should be placed **_left_** to the title. This is discussed wuth Brreg and Nav. https://altinndevops.slack.com/archives/C048MUWHJ9E/p1681895291687259 
- It should not be possible to put accordions within accordions

```[tasklist]
### Tasks
- [x] https://github.com/digdir/designsystem/issues/624
- [ ] https://github.com/digdir/designsystem/issues/292
- [ ] https://github.com/digdir/designsystem/issues/293
- [ ] https://github.com/digdir/designsystem/issues/625
- [ ] https://github.com/digdir/designsystem/issues/1242
- [ ] https://github.com/digdir/designsystem/issues/626
```
