### ISSUE TITLE
Pattern: Error messages

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#751]
In Altinn 3 we started to write about this, but we need to improve the article: https://www.designsystemet.no/monstre/feilmeldinger

Relevant information and links: 
-  Aksel om feilmeldinger i skjema: https://aksel.nav.no/god-praksis/artikler/skjemavalidering?tema=skjemaer 
- Elmer: https://brukskvalitet.brreg.no/elmer3/
- UU-tilsynet: https://www.uutilsynet.no/veiledning/skjema/38#formidle_feil_i_skjema 
- NN Group: [NN Group - Error Messages Guidelines](https://www.nngroup.com/articles/error-message-guidelines/)
- NN Group - [How to Report Errors in Forms](https://www.nngroup.com/articles/errors-forms-design-guidelines/)

```[tasklist]
### Tasks
- [x] Se på eksisterende info for dette
- [x] Samle informasjon om feilmeldinger og validering
- [x] Skrive utkast
- [x] Sende utkast til gjennomsyn hos Dorte
- [x] Innarbeide kommentarer fra Dorte
- [x] Lage eksempler
- [x] Review
```

**Comment by Ildest** [comment]
Teksten er skrevet og kvalitetssikret, klar til levering. Fant ikke noe "komponentområde" for den i Figma, så har spurt @mrosvik på Slack om hvor jeg ska legge den.

**Comment by mrosvik** [comment]
Jeg må lage litt eksempler her før vi kan ta denne videre.

**Comment by mimarz** [comment]
@mrosvik is reviewing this
