### ISSUE TITLE
ToggleGroup: Write guidelines for usage

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#806]
```[tasklist]
### Tasks
- [x] Use soure aksel.nav.no
- [x] Write draftwith markdown
- [x] Add draft to this issue
- [x] Set to Marianne
- [x] Set status Ready for review
```

**Comment by Ildest** [comment]
Lagt til Word-fil i Teams

**Comment by Ildest** [comment]
Status by 21. March: In progress by Ann-Elisabeth

**Comment by Ildest** [comment]
# `ToggleGroup` 

Med `ToggleGroup` kan brukerne velge alternativer som påvirker innholdet på en side. Komponenten består av en gruppe knapper som henger sammen, der kun én knapp er mulig å velge om gangen.

< Komponenten med tilhørende props > 

## Slik bruker du `ToggleGroup`
[Her beskriver utviklere/designere hvordan du teknisk tar den i bruk.]

Plasser helst innholdet du skal styre rett etter ToggleGroup i DOM-en. Hvis ikke, bør du bruke aria-controls på `ToggleGroup` for å knytte komponenten til den containeren for innholdet som endrer seg.

## Varianter av `ToggleGroup`
[Her kan vi for eksempel vise eksempler på Group label, Item label, Ikon, Fill og med tooltip.]

### `Navn på varianten`
Ett avsnitt om varianten og når den skal brukes.

[Eksempel]

### Størrelser
Vi har medium og small ToggleGroup. Medium er standard. Velg small hvis grensesnittet er komprimert.

### Handling eller nøytral
Vi kan velge mellom å bruke `ToggleGroup` med blå (action) eller grå (neutral). Nøytral passer til handlinger som vi gjerne vil tone ned. 

[Eksempel]

### Med eller uten ledetekst
Vi kan bruke `ToggleGroup` med og uten ledetekst. En ledetekst gjør det lettere for brukerne å skjønne hva de skal bruke komponenten til. Hvis vi velger å bruke den uten ledetekst, er det viktig at knappeteksten eller ikonene beskriver valgene godt.

[Eksempel]

### Innholdet på knappene
`ToggleGroup` kan ha tre typer innhold:

- Bare tekst.
- Tekst med ikon til venstre for teksten.
- Bare ikon.

Velg alternativet «Bare ikon» kun når du vet at brukerne vil forstå ikonet. Det kan for eksempel være ekspertbrukere eller brukere av interne tjenester, som kjenner symbolene  i den aktuelle `ToggleGroup` godt.

## Eksempler
[Lag tilsvarende Unngå/Gjør-eksemplene med relevant innhold for oss, fra ToggleGroup - aksel.nav.no.]

## Retningslinjer for `ToggleGroup`
Det bør være minst to, men ikke flere enn fem valg i en `ToggleGroup`. Trenger vi flere valg enn fem, bruker vi heller `Select`.

Passer til å
- filtrere innhold i lister og tabeller
- veksle mellom datavisning og innhold, for eksempel mellom tabell og graf
- styre hvilke felter i et skjema som skal vises

Passer ikke til å
- bruke som skjemaelement – bruk heller `RadioGroup` eller `Checkbox`
- navigere – bruk heller `Tabs` hvis det dreier seg om panelnavigasjon

### Gi nok plass til komponenten
Pass på at hele komponenten får plass på skjermen og at alle valgene er godt synlig for brukerne. I grensesnitt med liten plass, for eksempel på mobil, kan vi bruke `Select` i stedet.

[Lag tilsvarende Unngå -eksemplene med relevant innhold for oss, se avsnittet Plassering i ToggleGroup - aksel.nav.no]

### Bruk hint til å forklare handlinger
Forklar gjerne handlingene som er tilgjengelige i en `ToggleGroup` med `Tooltip`. Det er ekstra viktig når vi kun bruker ikoner.

## Tekst i komponenten
Ha gjerne med en ledetekst for gruppen, som forklarer hva valgene gjelder. Skriv tydelige tekster for valgene i komponenten, og pass på at de har samme språklige form. Ta med hint i `Tooltip`, særlig hvis du bare viser ikoner.

## Tilgjengelighet
`ToggleGroup` har standard fokusindikator (ramme).
Vi bruker «roving tabindex» for å håndtere fokusbevegelse mellom knappene. 

[Spør eventuelt en utvikler på teamet om å se gjennom og legge til stoff, eller finne stoff som går utover WCAG.]

### Tastaturinteraksjon (tabell med to kolonner)

Tast eller tastekombinasjon 	Interaksjon 
Tab 	Flytter fokuset til den aktive toggle-knappen.
Shift+Tab 	Flytter fokuset til elementet før `ToggleGroup` i tabindex.
Mellomrom	Velger en knapp.
Enter 	Velger en knapp. 
Pil ned 	Flytter fokuset til neste knapp i gruppa. 
Pil høyre 	Flytter fokuset til neste knapp i gruppa.
Pil opp	Flytter fokuset til forrige knapp i gruppa.
Pil venstre	Flytter fokuset til forrige knapp i gruppa.
Home 	Går til første knapp i gruppa.
End 	Går til siste knapp i gruppa. 

### Kilde
aksel.nav.no
