### ISSUE TITLE
New component: Modal

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#82]
## Related information and insight

- https://design.entur.org/komponenter/layout-og-flater/modal
- https://aksel.nav.no/komponenter/core/modal
- https://carbondesignsystem.com/components/modal/code/
- https://designsystem.dk/komponenter/modal/

## Modal specification
The Modal Component should be used to display content in a  overlaying window of the current page or screen. It provides a focused and contextual interaction for users without navigating away from the main content.

### Requirements
- Should support various types of content, including text, images, form-elements, buttons, link, lists, etc.
- Should support keyboard navigation, allowing users to interact using the keyboard alone.
- Should support scrolling within the modal if the content exceeds the viewport's height.
- Should support different languages.
- Should be responsive and adapt to different screen sizes, ensuring optimal usability on desktops, tablets, and mobile devices.
- Should follow accessibility standards, including proper semantic markup, correct use of ARIA attributes and keyboard accessibility. It should provide text alternatives for the icons.

Underlying content: 
- Should create a visually distinct overlay to darken the underlying content.
- Should prevent interaction with the underlying content while the modal is active.
- Clicking outside the modal window or on the overlay should close the modal.

To be considered:
- We should consider if the modal should come in different sizes with different spacing. 
- We should consider if the modal should support brand-colors.
- We should consider if the modal shall provide a close button in top or a button in bottom to dismiss the modal to allow users to exit the overlay.

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/585
- [ ] https://github.com/digdir/designsystem/issues/586
- [ ] https://github.com/digdir/designsystem/issues/587
- [x] Modal: WCAG-Test
```

**Comment by mrosvik** [comment]
The `Modal` component is ready for use: https://storybook.designsystemet.no/?path=/docs/felles-modal--docs
