### ISSUE TITLE
Server side rendering (SSR & RSC) support

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#823]
Edited by @mimarz 

Good introduction to SSR and React Server Components, read [this](https://www.joshwcomeau.com/react/server-components/).

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/860
- [ ] https://github.com/digdir/designsystem/issues/861
- [ ] https://github.com/digdir/designsystem/issues/863
- [ ] https://github.com/digdir/designsystem/issues/862
- [ ] https://github.com/digdir/designsystem/issues/1254
```

```[tasklist]
### Verify that these bugs are resolved
- [ ] #812 
- [ ] #817 
``` 

### **Description of issue:**
The components don't work properly with client- and server components with Next.js' new App Router. They also don't work with SSR in general.

**Issue when using client components:**

The computed styles from the CSS modules don't load with the payload. This creates a delay on the initial page load of the styles being loaded. The user will see the page without styles for a brief second before the computed styles load. Example of it happening in [this](https://streamable.com/och0eo) video.

**Issue when using server components:**

When using server components, no computed styles are loaded. The Next app also crashes before anything is shown because client-side code is used.

**Comment by Thuneer** [comment]
### **Looked into this issue further:**

Looks like CSS files has to be sent with the server for SSR to work rather than using computed styles. Mantine scans all its CSS modules and generates CSS files for each component. We tested this on our internal React library and this works very well. We made [this](https://github.com/felleslosninger/tlp-react/blob/main/packages/react/scripts/generate-css.ts) script that generates a list of CSS files that we make available in our NPM package. THis solves both CSR and SSR when it comes to computed styles.

**Tested the components in a Next.js SSR app:**

Using `NPM link` I tested the components one by one locally in a Next.js app. Had to build the library for each component because if the library contained client code the entire app just crashed.

**Client side code that fails:**

* `React.createContext` is used a few places in the library.
* `useState` is used a few places.
* `Pagination` gave an error because of the `onClick` `Button` prop. Probably client-side prop.

**Comment by mimarz** [comment]
Meeting 26.09.23 with @Thuneer @mimarz @Barsnes @framitdavid @Magnusrm 

After reviewing our findings and testing we decided on a set of tasks we wanted to do as in imidiate fix and short term support for SSR. 

Since we already have two developers working on components and some specification is still needed for others, @Barsnes will work on these task now during his stay with us as he has already deep-dived into the problem, and familiarised with what changes needs to be done to fix this. 

On top of that we want this fixed before v1 as we are getting feedback already now from our users wanting to use NextJs and Remix which are SSR frameworks.

**Comment by mimarz** [comment]
We solved RSC by using `use client` as most components depend on React context for a11y and composability reasons.

**Comment by imp-dance** [comment]
> We solved RSC by using `use client` as most components depend on React context for a11y and composability reasons.

Using the current RC version ( `1.0.0-rc.3`)  this does not seem to be the case. As an example, the Accordion and RadioGroup components both break my RSC setup if I don't explicitly set `"use client"` in a wrapper component.

**Comment by mimarz** [comment]
> > We solved RSC by using `use client` as most components depend on React context for a11y and composability reasons.
> 
> Using the current RC version ( `1.0.0-rc.3`) this does not seem to be the case. As an example, the Accordion and RadioGroup components both break my RSC setup if I don't explicitly set `"use client"` on my own in a wrapper component.

Interesting, they are crashing because we call `window` in `Accordion` (for proper expand/collapse animation) and `RadioGroup` uses `React.Context`, however we are also adding `"use client"` to all our dist files. 🤔

**Comment by imp-dance** [comment]
> Interesting, they are crashing because we call `window` in `Accordion` (for proper expand/collapse animation) and `RadioGroup` uses `React.Context`, however we are also adding `"use client"` to all our dist files. 🤔

Yeah that is interesting. I can confirm in my node_modules folder as well both the CJS and ESM builds have `"use client"` in the Accordion file at least.

**Comment by Barsnes** [comment]
> > Interesting, they are crashing because we call `window` in `Accordion` (for proper expand/collapse animation) and `RadioGroup` uses `React.Context`, however we are also adding `"use client"` to all our dist files. 🤔
> 
> Yeah that is interesting. I can confirm in my node_modules folder as well both the CJS and ESM builds have `"use client"` in the Accordion file at least.

What setup are you using for RSC? Would be ideal if we can recreate this in a codesandbox

**Comment by imp-dance** [comment]
> What setup are you using for RSC? Would be ideal if we can recreate this in a codesandbox

I'm using NextJS 14 with React 18:

```
{
  "name": "next-test-designsystemet",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@digdir/designsystemet-css": "0.9.1-alpha.3",
    "@digdir/designsystemet-react": "1.0.0-rc.3",
    "@digdir/designsystemet-theme": "1.0.0-rc.3",
    "next": "14.2.3",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.3",
    "typescript": "^5"
  }
}
```

I import the stylesheets (as well as my own tokens) in the root layout:

```typescript
import "@digdir/designsystemet-css";
import "@digdir/designsystemet-theme";
import "./ds-theme.css";
```

And then try using `Accordion`,  or `Radio` (group) in the root page. 

I also tried setting up a Stackblitz project to reproduce this but it's not resolving the RC designsystemet package for some reason.

**Comment by Barsnes** [comment]
> > What setup are you using for RSC? Would be ideal if we can recreate this in a codesandbox
> 
> I'm using NextJS 14 with React 18:
> 
> ```
> {
>   "name": "next-test-designsystemet",
>   "version": "0.1.0",
>   "private": true,
>   "scripts": {
>     "dev": "next dev",
>     "build": "next build",
>     "start": "next start",
>     "lint": "next lint"
>   },
>   "dependencies": {
>     "@digdir/designsystemet-css": "0.9.1-alpha.3",
>     "@digdir/designsystemet-react": "1.0.0-rc.3",
>     "@digdir/designsystemet-theme": "1.0.0-rc.3",
>     "next": "14.2.3",
>     "react": "^18",
>     "react-dom": "^18"
>   },
>   "devDependencies": {
>     "@types/node": "^20",
>     "@types/react": "^18",
>     "@types/react-dom": "^18",
>     "eslint": "^8",
>     "eslint-config-next": "14.2.3",
>     "typescript": "^5"
>   }
> }
> ```
> 
> I import the stylesheets (as well as my own tokens) in the root layout:
> 
> ```ts
> import "@digdir/designsystemet-css";
> import "@digdir/designsystemet-theme";
> import "./ds-theme.css";
> ```
> 
> And then try using `Accordion`, or `Radio` (group) in the root page.
> 
> I also tried setting up a Stackblitz project to reproduce this but it's not resolving the RC designsystemet package for some reason.

Are you by any chance using dot notation to use the components? This is not available for use in server components

**Comment by imp-dance** [comment]
> Are you by any chance using dot notation to use the components? This is not available for use in server components

Yes I was, was not aware of that! Indeed when I change them from for example `Radio.Group` -> `RadioGroup` it now works properly. Strange how that is affected.

Maybe worth noting in the documentation, either on a generic "RSC info" page, or as a notice below any example that uses dot notation.

**Comment by Barsnes** [comment]
Closing this, and we will make sure to document this is the future
