### ISSUE TITLE
New component: Pagination

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#83]
## Related information and insight
- [Comments about pagination from NNGroup](https://www.nngroup.com/articles/item-list-view-all/):
  - Most users don’t want to customize; they prefer to simply use the default settings. It is thus the designer’s responsibility to pick the optimal default setting that will benefit the most users, because that’s all most users will ever experience. Customization features are user interfaces in their own right and have their own usability problems, especially when designers go overboard and offer users too many choices.
- https://designsystem.dk/komponenter/paginering/
- https://aksel.nav.no/komponenter/core/pagination
- https://design.entur.org/komponenter/navigasjon/pagination
- https://design-system.service.gov.uk/components/pagination/
- https://carbondesignsystem.com/components/pagination/code/
- See pagination used in [altinn tables](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=7666%3A43015&t=fgu4e3XDW9eMAE9U-1)

## Paginaton Specification
The Pagination Component should be used to divide a large set of content into smaller, more manageable sections, allowing users to navigate through the content efficiently. It should:
   - Display a set of page numbers and navigation controls
   - Indicating the current page
   - Allow users to navigate to other pages by clicking on the corresponding page number or the Prev/Next-buttons.

### Requirements 
- Should be responsive and adapt its display to different screen sizes and orientations. The number of page numbers displayed may vary depending on the available space / viewport.
- Should follow accessibility standards, including proper semantic markup, correct use of ARIA attributes and keyboard accessibility. It should provide text alternatives for the icons.
- Should be build by using the button component from FDK and the correct Design tokens (see Figma).
- Should support different languages.
- Should come in three sizes: `small`, `medium`, `large`
- The active Page should be highlighted to provide visual feedback to the user.
- Should use status icons from [Navs icon library](https://aksel.nav.no/ikoner): `ChevronLeft` , `ChevronRight` 
- "< Previous" and "Next >" buttons should support configurable labels so that it could be used with only arrow icons (no text)
- Display a set of page numbers within a defined range. Configurable options to control the number of page numbers displayed.
- Should support polymorphism component, because SSR may require anchor tags instead of button.

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/539
- [ ] https://github.com/digdir/designsystem/issues/540
- [ ] https://github.com/digdir/designsystem/issues/541
- [x] Pagination: WCAG-test
```

![image](https://github.com/digdir/designsystem/assets/1464915/b08bf9cc-1698-41b6-b0a2-9b17aa6019c0)

**Comment by mrosvik** [comment]
FDK tester ut å bruke Aksel sin paginering-komponent i FDK-designet. https://aksel.nav.no/komponenter/core/pagination
