### ISSUE TITLE
Mønstre og god praksis

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#845]
I rapporten "[Digital hele livet med bedre brukeropplevelse](https://www.digdir.no/sammenhengende-tjenester/digital-hele-livet-med-bedre-brukeropplevelse/4405)" er det funnet flere [konkrete problemer med brukskvalitet](https://github.com/digdir/innsiktsbibliotek/issues/3) som kan forbedres dersom vi samarbeider om å etablere like mønstre på tvers av offentlige tjenester. Når vi bruker etablerte mønstre som innbyggerne kjenner igjen på tvers kan løsningene bli mer intuitive og bidra til mindre digitalt utenforskap.

I arbeidsmøter med Nav, Skatt, Brreg og Arbeidstilsynet har vi snakket om hvilke mønstre som gir verdi å etablere på tvers. Vi vil sammen prioritere dem etter hva som har lavest innsats og samtidig høy verdi.

```[tasklist]
### Mønstre som kan gi verdi å etablere på tvers:
- [ ] https://github.com/digdir/designsystem/issues/844
- [ ] https://github.com/digdir/designsystemet/pull/2096
- [ ] Navigasjonselementer i skjema / Ulike navigeringsknapper / Rekkefølge på knapper
- [ ] Feilmeldinger
- [ ] Skjemavalidering
- [ ] Indikere tidsbruk og antall steg i utfylling av skjema
- [ ] Antall spørsmål per side
- [ ] Slett/fjern
- [ ] Vanskelig å finne "Logg inn"
- [ ] Automatisk utlogging / Tidsavbrudd
- [ ] Timebestilling
- [ ] Bytte mellom privat og virksomhet
- [ ] Ulike navigasjonsretninger
- [ ] Innhold i footer
- [ ] Hvordan bytte språk
- [ ] Begreper som varierer på tvers
- [ ] Hvordan spør vi brukeren om fødselsnummer
- [ ] Hvordan spør vi brukeren om dato
- [ ] Hvordan spør vi brukeren om adresse
- [ ] Hvordan spør vi brukeren om telefonnummer
- [ ] Hvordan spør vi brukeren om bankkonto-detaljer
- [ ] Filtrering
- [ ] Bruk av pop-ups
- [ ] Bruk av nedtrekksmenyer
```

---------------

Vi ønsker å invitere inn andre som har innsikt, kunnskap eller kjennskap til aktuelle temaer i arbeidsmøter fremover. 

Slik går vi frem per mønster:
1: Samle innsikt for mønsteret i Miro-brett. Oppfordre andre til å legge inn tanker og innsikt. Noe av det som deles av innsikt kan kanskje etterpå legges i [Felles innsiktsbibliotek](https://github.com/digdir/innsiktsbibliotek)?
2: Arbeidsmøte: Diskusjon og vurdering av den innsikten vi har. 
3: Lage et forslag til retningslinjer, anbefalinger og eksempler
4: Arbeidsmøte: Gjennomgang av forslag og innspill. 
5: Dele på https://www.designsystemet.no/monstre

**Comment by mrosvik** [comment]
Prioritering av mønstre 13.09.2023

![Image](https://github.com/digdir/designsystem/assets/1464915/ab9bfbbd-6e8c-4a90-a1d7-e55029bdb13d)

**Comment by mrosvik** [comment]
Moved to discussions: https://github.com/digdir/designsystemet/discussions/categories/m%C3%B8nster-for-innbyggertjenester
