### ISSUE TITLE
New component: Stepper

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#85]
## Related issues or relevant information?
- https://github.com/Altinn/app-frontend-react/issues/97
- https://github.com/Altinn/app-frontend-react/issues/188 (Progress indicator made for "Elevundersøkelsen")

### Related research: 
- https://www.linkedin.com/posts/vitalyfriedman_ux-design-activity-7127577055029796864-0JVK?utm_source=share&utm_medium=member_ios

### Other Stepper components
- Carbon progress-indicator: https://carbondesignsystem.com/components/progress-indicator/usage/
- Carbon progress-bar: https://carbondesignsystem.com/components/progress-bar/usage/
- Gov UK: https://design-system.service.gov.uk/patterns/step-by-step-navigation/
- Fælles designsystem: https://designsystem.dk/komponenter/trinindikator/
- Entur: https://design.entur.org/komponenter/navigasjon/stepper
- Nav: https://aksel.nav.no/komponenter/core/stepper
- Atlassian: https://atlassian.design/components/progress-tracker/examples (See also progress bar and progress indicator)

## Specification and requirements
- _Add specification and requirements_

```[tasklist]
### Tasks
- [ ] Stepper: Write about specification, requirements and scope in this issue
- [ ] https://github.com/digdir/designsystem/issues/1120
- [ ] https://github.com/digdir/designsystem/issues/1121
- [ ] https://github.com/digdir/designsystem/issues/1122
```

**Comment by eirikbacker** [comment]
...kanskje vi skulle gjort som **Datepicker**: Laget en side hvor vi viser frem alternativ til stepper først? 🤔

Stepper er litt artig komponent, for mange vil ha det, men vår erfaring i Mattilsynet er at det er mest på gammel vane - for de er egentlig ikke så praktisk å bruke (tenk på hvor ofte ser du en stepper i et operativsystem f.eks?). Horisontale steppere er ofte svært vanskelig på mobil, vertikale er nyttig for å vise en tidslinje, men stort sett det, og de tar mye plass.

Dersom man skal vise fremdrift i et skjema f.eks, kan det være like effektivt å ha "Del 1 av 10: Hvem er du?" som tittel, eller som select for å hoppe mellom steg, og vanlige neste/forrige-knapper i bunn.

Vi har også flere produkter som har begynt å bruke details/utvidbare-felt med tall foran for å visualisere oppdeling i skjemaflyt:

<img width="1424" height="1304" alt="Image" src="https://github.com/user-attachments/assets/bb02eb0f-efee-4f77-a7ce-abd1f145b8b4" />

**Comment by mrosvik** [comment]
Closing this, as we have a discussion thread and haven’t yet decided whether to create a component or a page with recommendations. https://github.com/digdir/designsystemet/discussions/1820
