### ISSUE TITLE
New component: Search

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#88]
## Related information and insight
- https://designsystem.dk/komponenter/search/
- https://aksel.nav.no/komponenter/core/search
- https://carbondesignsystem.com/components/search/usage/

Relevant issues: 
- https://github.com/digdir/designsystem/pull/206 

## Specification and requirements
- _Add specification and requirements_

```[tasklist]
### Tasks
- [ ] Write about specification, requirements and scope in this issue
- [ ] https://github.com/digdir/designsystem/issues/856
- [ ] Search: Write guidelines for usage
- [ ] https://github.com/digdir/designsystem/issues/948
- [ ] Search: WCAG-Test
```

**Comment by mrosvik** [comment]
The search component is ready for use: https://storybook.designsystemet.no/?path=/docs/felles-search--docs
