### ISSUE TITLE
New component: Switch

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#89]
## Related information and insight

- Toggle and Switch is both used as name for this component
- UX Planet: https://uxplanet.org/ui-switch-component-3f29bc7f4f45
- https://aksel.nav.no/komponenter/core/switch
- https://design.entur.org/komponenter/skjemaelementer/switch
- https://designsystem.dk/komponenter/toggle/
- https://carbondesignsystem.com/components/toggle/usage/

## Switch specification
TheSwitch component should be used to enable and disable different options.

- The switch should have only two states: on and off
- The change should be applied immediately
- Use clear colors to indicate the on and off state to the user
- To indicate the switch’s purpose, provide a clear label
- Should be large enough to be easily tapped or clicked by the user.
- _Add requirements and specification_

```[tasklist]
### Tasks
- [x] Write about specification, requirements and scope in this issue
- [ ] https://github.com/digdir/designsystem/issues/644
- [ ] https://github.com/digdir/designsystem/issues/645
- [ ] https://github.com/digdir/designsystem/issues/646
- [ ] https://github.com/digdir/designsystem/issues/647
```

**Comment by mrosvik** [comment]
The `switch` component is ready for use: https://storybook.designsystemet.no/?path=/docs/felles-switch--docs
