### ISSUE TITLE
New component: Table

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#90]
## Related information and insight
- Table design is started based on a need from [Altinn Studio](https://www.figma.com/file/wnBveAG2ikUspFsQwM3GNE/Altinn-Studio-Apps?node-id=14756%3A10448&t=863BKdTn5UPuOLAI-1)
- https://aksel.nav.no/komponenter/core/table
- https://design.entur.org/komponenter/layout-og-flater/table
- https://designsystem.dk/komponenter/tables/
- https://atlassian.design/components/table-tree/examples
- https://design-system.service.gov.uk/components/table/

Relevant issues: 
- https://github.com/digdir/designsystem/pull/206 

## Specification and requirements
[Figma link](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=24926%3A12699&mode=design&t=S3tWlrzUbnjqvUnp-1)

**Figma Tasks**
- [x] Add bolder font weight to headers. Our paragraph component do not support this right now. We need to decide if we should use a label (in figma) or expand our paragraph with new font weight options. 
- [x] ~~Add hover state to rows~~ Not possible with current Figma setup
- [x] Add border version
- [x] Add sort styling
- [x] Sticky header

**Features**
- [ ] Zebra stripes for better readability
  - [ ] We got feedback that we should make sure that the "stripes" are not connected to the row. Meaning that if you use sorting on the table the stripes should not follow the row and cluttering up the zebra stripes
  - [ ] Remove lines between the rows when zebra is on
- [ ] Support for headers on column and row

**Discussion or examples for storybook**
- [ ] Hover on rows [Example from Aksel](https://aksel.nav.no/komponenter/core/table)
- [ ] Sticky header
- [ ] Do we need a version with border? See example below
- [ ] Highlight the use of `caption`
- [ ] How to use form components correctly in a table
- [ ] Sorting
- [ ] Do we need a description list versjon? I have seen this used a lot different places, solved in different ways. Might be good for "check answer" patterns for example. 

Border example:
<img width="768" alt="Skjermbilde 2024-01-04 kl  09 21 26" src="https://github.com/digdir/designsystemet/assets/33222679/36c1b52a-ab82-4f91-aebf-e09d8efddc86">

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/209
- [x] Write about specification, requirements and scope in this issue
- [x] https://github.com/digdir/designsystem/issues/795
- [ ] https://github.com/digdir/designsystemet/issues/1343
- [ ] https://github.com/digdir/designsystemet/issues/1342
- [ ] https://github.com/digdir/designsystemet/issues/1341
- [x] Table: WCAG-Test
```

**Comment by mrosvik** [comment]
The `Table` component is ready for use: https://storybook.designsystemet.no/?path=/docs/felles-table--docs
