### ISSUE TITLE
Improvements: Tabs

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#91]
### Relevant information?

- https://aksel.nav.no/komponenter/core/tabs
- https://design.entur.org/komponenter/layout-og-flater/tabs
- https://designsystem.dk/komponenter/faneblade/
- https://design-system.service.gov.uk/components/tabs/
- https://carbondesignsystem.com/components/tabs/usage/
- https://atlassian.design/components/tabs/examples

### Existing component: 
https://digdir.github.io/designsystem/?path=/docs/kjernekomponenter-tabs--docs 
(made in Altinn designsystem, has some issues)

### Related issues: 

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/363
- [ ] https://github.com/digdir/designsystem/issues/362
- [x] Line-height should be 1.5 unitless
- [ ] https://github.com/digdir/designsystem/issues/590
- [ ] https://github.com/digdir/designsystem/issues/872
```
