### ISSUE TITLE
Rename resources to `designsystemet`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#918]
To conform to our product name and website, we should rename our packages to match.

Please update this issue with any findings of places we have linked to using the current/old name. Places such as Slack bookmarks or other places.

## New package structure:

- `@digdir/design-system-react` -> `@digdir/designsystemet-react`
- `@digdir/design-system-tokens` -> `@digdir/designsystemet-theme`
- `@digdir/designsystemet-css` 

In npmjs.org, changed package names are counted as new package. 

For "old" packages we will have to make a deprecation publish with updated README pointing to new package and mark that package as deprecated. 

### Documentation

All code examples will need to be replaced/update with new package names.

- [ ] Write a good get started with our packages and font.

## New Github name:
- [ ] https://github.com/digdir/designsystemet

Changing github repository name will be a breaking change for everyone who has checked out the repository as the url for origin has changed. People will need to edit their local git config with new url.

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/1069
- [ ] https://github.com/digdir/designsystem/issues/1017
- [ ] https://github.com/digdir/designsystemet/issues/1645
- [x] Update documentation
- [ ] https://github.com/digdir/designsystem/issues/1010
```

**Comment by mimarz** [comment]
Any other places that needs to be renamed? Figma looks to be updated? @Febakke @Thuneer

**Comment by Barsnes** [comment]
I can't find any react components that use `export default`, so this issue can be closed without a PR.

**Comment by mimarz** [comment]
Done!
