### ISSUE TITLE
New component: Tooltip

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#93]
## Related information and insight
- https://aksel.nav.no/komponenter/core/tooltip
- https://design.entur.org/komponenter/feedback/tooltip
- https://designsystem.dk/komponenter/tooltip/
- https://carbondesignsystem.com/components/tooltip/usage/
- https://atlassian.design/components/tooltip/examples
- https://designsystem.digital.gov/components/tooltip/

Relevant issues: 
- https://github.com/digdir/designsystem/pull/206 

## Specification and requirements
- _Add specification and requirements_

```[tasklist]
### Tasks
- [x] Write about specification, requirements and scope in this issue
- [ ] https://github.com/digdir/designsystem/issues/1093
- [ ] https://github.com/digdir/designsystemet/issues/1494
- [ ] https://github.com/digdir/designsystem/issues/911
- [x] Tooltip: WCAG-Test
```

**Comment by mrosvik** [comment]
The `Tooltip` component is ready for use: https://storybook.designsystemet.no/?path=/docs/felles-tooltip--docs
